In [33]:
import pandas as pd
import numpy as np
import networkx as nx
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
artists = pd.read_csv('data_by_artist.csv')
artists

artist_name  artist_id  danceability    energy   valence  \
0          Frank Sinatra     792507      0.384478  0.238017  0.364288   
1      Vladimir Horowitz     119107      0.343210  0.118844  0.225951   
2            Johnny Cash     816890      0.619803  0.449381  0.680662   
3         Billie Holiday      79016      0.572637  0.201368  0.498934   
4              Bob Dylan      66915      0.512598  0.477932  0.551934   
...                  ...        ...           ...       ...       ...   
5849     Natalie La Rose    3359519      0.830000  0.520000  0.735000   
5850          Sarah Ross    3381566      0.721000  0.944000  0.626000   
5851              Rotimi    3410250      0.637000  0.501000  0.431000   
5852  Jillian Jacqueline    3455945      0.547000  0.672000  0.283000   
5853         Jaira Burns    3639618      0.566000  0.769000  0.385000   

           tempo   loudness  mode  key  acousticness  instrumentalness  \
0     110.181698 -14.271141     1    5      0.735648          0.020855   
1      94.900679 -23.193418     1    1      0.990070          0.879508   
2     115.037747 -11.593104     1   10      0.685637          0.022647   
3     109.912172 -13.225966     1    5      0.908499          0.013064   
4     126.160149 -11.184330     1    7      0.562567          0.034211   
...          ...        ...   ...  ...           ...               ...   
5849  104.990000  -8.714000     1    0      0.000792          0.000013   
5850   85.002000  -5.982000     1    8      0.013000          0.000000   
5851  103.993000  -6.148000     0    0      0.229000          0.000059   
5852  155.791000  -5.023000     1   11      0.304000          0.000000   
5853  170.036000  -4.342000     1    7      0.018300          0.000000   

      liveness  speechiness  duration_ms  popularity  count  
0     0.232106     0.049614  189179.9255   26.004383   1369  
1     0.183812     0.043360  266541.1251    3.592378   1207  
2     0.242243     0.098216  162279.2672   26.614130   1104  
3     0.217727     0.062432  185131.4530   15.621005   1095  
4     0.308978     0.064535  256713.4203   30.860806   1092  
...        ...          ...          ...         ...    ...  
5849  0.065600     0.037600  189907.0000   64.000000      1  
5850  0.320000     0.159000  262760.0000   52.000000      1  
5851  0.099000     0.187000  185461.0000   71.000000      1  
5852  0.099600     0.049600  213133.0000   58.000000      1  
5853  0.108000     0.087200  191100.0000   74.000000      1  

[5854 rows x 16 columns]

In [14]:
years = pd.read_csv('data_by_year.csv')
years

year  danceability    energy   valence       tempo   loudness  mode  key  \
0   1921      0.425661  0.236784  0.425495  100.397758 -17.095437     1    7   
1   1922      0.480000  0.237026  0.534056  101.376139 -19.179958     1   10   
2   1923      0.568462  0.246936  0.624788  112.456598 -14.373882     1    0   
3   1924      0.548654  0.347033  0.668574  120.653359 -14.202304     1   10   
4   1925      0.571890  0.264373  0.616430  115.671715 -14.516707     1    5   
..   ...           ...       ...       ...         ...        ...   ...  ...   
95  2016      0.599976  0.592877  0.430769  119.070344  -7.949913     1    0   
96  2017      0.612286  0.586739  0.414465  116.840277  -8.422697     1    1   
97  2018      0.664930  0.590591  0.447141  122.004325  -7.253666     1    1   
98  2019      0.644215  0.578796  0.465856  118.868163  -8.041738     1    1   
99  2020      0.673077  0.611914  0.482755  121.228704  -7.204024     1    1   

    acousticness  instrumentalness  liveness  speechiness  duration_ms  \
0       0.895823          0.322330  0.215814     0.077258  229911.9141   
1       0.939236          0.440470  0.238647     0.115419  167904.5417   
2       0.976329          0.401932  0.236656     0.098619  178356.3018   
3       0.935575          0.583955  0.237875     0.090210  188461.6498   
4       0.965422          0.408893  0.243094     0.115457  184130.6996   
..           ...               ...       ...          ...          ...   
95      0.280290          0.074646  0.180198     0.107298  219400.7638   
96      0.289916          0.098209  0.194218     0.111752  209343.6130   
97      0.271941          0.035948  0.171781     0.128140  200919.1190   
98      0.289298          0.076518  0.167161     0.124799  197733.1330   
99      0.247374          0.039052  0.177048     0.143505  197114.6623   

    popularity  
0     0.351562  
1     0.138889  
2     5.727811  
3     0.603376  
4     2.707224  
..         ...  
95   61.371254  
96   64.861500  
97   67.276000  
98   69.655500  
99   63.111048  

[100 rows x 14 columns]

In [15]:
full = pd.read_csv('full_music_data.csv')
full

artist_names artists_id  danceability  energy  valence  \
0      ["Fat Freddy's Drop"]   [178301]         0.600   0.365    0.131   
1      ["Fat Freddy's Drop"]   [178301]         0.874   0.326    0.179   
2      ["Fat Freddy's Drop"]   [178301]         0.670   0.531    0.336   
3       ["Alexander O'Neal"]   [625201]         0.761   0.702    0.850   
4       ["Alexander O'Neal"]   [625201]         0.661   0.828    0.902   
...                      ...        ...           ...     ...      ...   
98335             ['ZZ Top']   [690254]         0.276   0.892    0.715   
98336             ['ZZ Top']   [690254]         0.700   0.592    0.906   
98337             ['ZZ Top']   [690254]         0.709   0.709    0.863   
98338             ['ZZ Top']   [690254]         0.552   0.651    0.533   
98339             ['ZZ Top']   [690254]         0.546   0.864    0.863   

         tempo  loudness  mode  key  acousticness  instrumentalness  liveness  \
0      130.046   -13.083     0    9       0.06720          0.585000    0.0921   
1      119.620   -13.302     0   11       0.01360          0.148000    0.0993   
2      139.385    -8.267     0    9       0.01560          0.345000    0.3060   
3      104.773    -8.523     1    7       0.10800          0.000031    0.0935   
4      115.078   -12.673     0   11       0.27600          0.000001    0.2870   
...        ...       ...   ...  ...           ...               ...       ...   
98335   80.475    -7.035     1   11       0.40900          0.000000    0.7140   
98336  109.847   -10.434     1   11       0.10800          0.018400    0.1180   
98337  111.544   -12.023     1    2       0.11800          0.000011    0.1250   
98338  161.548   -10.624     0    4       0.00494          0.034900    0.1320   
98339  145.652    -7.632     1    7       0.09080          0.008140    0.2770   

       speechiness  explicit  duration_ms  popularity  year release_date  \
0           0.0498         0       437200          54  2005         2005   
1           0.1310         0       581008          53  2005         2005   
2           0.0377         0       431293          55  2009     8/7/2009   
3           0.0389         0       304427          34  1991     1/1/1991   
4           0.0390         0       264933          37  1987    7/29/1987   
...            ...       ...          ...         ...   ...          ...   
98335       0.0893         0       115973          33  1975    4/18/1975   
98336       0.0681         0       263627          32  1976   11/29/1976   
98337       0.0370         0       158400          31  1987         1987   
98338       0.2290         0       232533          43  1992    4/13/1992   
98339       0.0393         0       137240          43  2005    7/19/2005   

                      song_title (censored)  
0                                     Ernie  
1                             Wandering Eye  
2                                  The Raft  
3                              All True Man  
4      (What Can I Say) To Make You Love Me  
...                                     ...  
98335        Jailhouse Rock - **** Remaster  
98336                        It's Only Love  
98337                              Balinese  
98338             La Grange - **** Remaster  
98339                                  ****  

[98340 rows x 19 columns]

In [16]:
influence = pd.read_csv('influence_data.csv')
influence

influencer_id  influencer_name influencer_main_genre  \
0             759491    The Exploited              Pop/Rock   
1              25462           Tricky            Electronic   
2              66915        Bob Dylan              Pop/Rock   
3              71209    Leonard Cohen              Pop/Rock   
4              91438     The Gun Club              Pop/Rock   
...              ...              ...                   ...   
42765         580300   Sufjan Stevens              Pop/Rock   
42766         261309      Vybz Kartel                Reggae   
42767         467203  Michael Jackson                  R&B;   
42768        2518003          Popcaan                Reggae   
42769        2896351        Tommy Lee                Reggae   

       influencer_active_start  follower_id      follower_name  \
0                         1980           74     Special Duties   
1                         1990          335          PJ Harvey   
2                         1960          335          PJ Harvey   
3                         1950          335          PJ Harvey   
4                         1980          335          PJ Harvey   
...                        ...          ...                ...   
42765                     1990      3661738  Rosemary & Garlic   
42766                     2000      3670556   Trinidad Cardona   
42767                     1960      3670556   Trinidad Cardona   
42768                     2000      3670556   Trinidad Cardona   
42769                     2000      3670556   Trinidad Cardona   

      follower_main_genre  follower_active_start  
0                Pop/Rock                   1980  
1                Pop/Rock                   1990  
2                Pop/Rock                   1990  
3                Pop/Rock                   1990  
4                Pop/Rock                   1990  
...                   ...                    ...  
42765            Pop/Rock                   2010  
42766                R&B;                   2010  
42767                R&B;                   2010  
42768                R&B;                   2010  
42769                R&B;                   2010  

[42770 rows x 8 columns]

In [18]:
len(influence)

42770

In [57]:
influenceGraph = nx.DiGraph()

In [ ]:
i = 0
while i < len(influence):
    influencer = artists[artists['artist_name'] == influence['influencer_name'][i]]
    influencer = influencer[['energy','valence', 'key', 'acousticness', 'instrumentalness', 'speechiness']]
    v1 = influencer.to_numpy()
    follower = artists[artists['artist_name'] == influence['follower_name'][i]]
    follower = follower[['energy','valence', 'key', 'acousticness', 'instrumentalness', 'speechiness']]
    v2 = follower.to_numpy()
    print(v1)
    print(v2)
    weight = cosine_similarity(v1, v2) * 1000
    print(weight)
    influenceGraph.add_edge(influence['influencer_name'][i], influence['follower_name'][i], weight = weight)
    i += 1

[[8.59571429e-01 4.19285714e-01 7.00000000e+00 3.69747140e-02
  4.04277900e-03 1.52171429e-01]]
[[8.65e-01 4.87e-01 9.00e+00 2.64e-02 1.85e-03 4.60e-02]]
[[999.49996324]]
[[0.63083333 0.55633333 0.         0.22453833 0.18496888 0.13008333]]
[[0.49487879 0.49157576 0.         0.18777163 0.14303846 0.03791818]]
[[993.96118588]]
[[0.47793205 0.5519337  7.         0.56256679 0.03421143 0.06453489]]
[[0.49487879 0.49157576 0.         0.18777163 0.14303846 0.03791818]]
[[119.24012292]]
[[0.25280685 0.33891781 9.         0.7297452  0.02733073 0.03877945]]
[[0.49487879 0.49157576 0.         0.18777163 0.14303846 0.03791818]]
[[65.12950161]]
[[0.80958333 0.547      9.         0.1136745  0.04136167 0.07655833]]
[[0.49487879 0.49157576 0.         0.18777163 0.14303846 0.03791818]]
[[104.80671488]]
[[5.67333333e-01 8.94333333e-01 5.00000000e+00 1.18533333e-01
  6.59333000e-04 6.27666670e-02]]
[[0.49487879 0.49157576 0.         0.18777163 0.14303846 0.03791818]]
[[197.64979263]]
[[0.463  0.578  9. 

[[931.99897876]]
[[7.2500000e-01 7.0000000e-01 9.0000000e+00 6.7400000e-02 3.5700000e-07
  8.2466667e-02]]
[[0.82040323 0.40042258 9.         0.01723142 0.17434948 0.05254193]]
[[999.19106012]]
[[0.66586667 0.36048667 2.         0.08857801 0.16252333 0.05264   ]]
[[0.82040323 0.40042258 9.         0.01723142 0.17434948 0.05254193]]
[[963.7399528]]
[[0.71646075 0.53921028 8.         0.21113931 0.17333124 0.09865981]]
[[0.82040323 0.40042258 9.         0.01723142 0.17434948 0.05254193]]
[[999.42134901]]
[[0.39708878 0.4946415  7.         0.46080888 0.04617556 0.03768605]]
[[0.82040323 0.40042258 9.         0.01723142 0.17434948 0.05254193]]
[[996.97626238]]
[[0.58708   0.69528   0.        0.1990712 0.1112598 0.084332 ]]
[[0.82040323 0.40042258 9.         0.01723142 0.17434948 0.05254193]]
[[92.38048631]]
[[0.90390756 0.33906177 4.         0.02006071 0.22803874 0.09990336]]
[[0.82040323 0.40042258 9.         0.01723142 0.17434948 0.05254193]]
[[989.8887884]]
[[0.79480952 0.56952381 9.    

[[0.34522154 0.58       9.         0.54480308 0.02934325 0.07171846]]
[[0.47179167 0.62066667 7.         0.5947375  0.29353897 0.04265   ]]
[[998.28129618]]
[[0.30053    0.44124    7.         0.54885    0.44933071 0.04484167]]
[[0.47179167 0.62066667 7.         0.5947375  0.29353897 0.04265   ]]
[[999.12289923]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]]
[[0.47179167 0.62066667 7.         0.5947375  0.29353897 0.04265   ]]
[[136.62752802]]
[[0.21066667 0.43933333 2.         0.93066667 0.93       0.05376667]]
[[0.47179167 0.62066667 7.         0.5947375  0.29353897 0.04265   ]]
[[879.29131147]]
[[0.25935519 0.45916132 2.         0.72938679 0.28788264 0.04763774]]
[[0.47179167 0.62066667 7.         0.5947375  0.29353897 0.04265   ]]
[[953.68535953]]
[[0.21763793 0.47844828 5.         0.83031035 0.25269384 0.05627069]]
[[0.47179167 0.62066667 7.         0.5947375  0.29353897 0.04265   ]]
[[996.50879017]]
[[0.23801673 0.36428824 5.         0.73564823 0.02085498 0

[[7.55e-01 8.24e-01 9.00e+00 1.57e-02 9.22e-06 4.53e-02]]
[[109.12941154]]
[[ 0.49138889  0.84563889 10.          0.46273611  0.12264449  0.06648333]]
[[7.55e-01 8.24e-01 9.00e+00 1.57e-02 9.22e-06 4.53e-02]]
[[998.32826303]]
[[ 0.69   0.79  11.     0.527  0.501  0.345]]
[[7.55e-01 8.24e-01 9.00e+00 1.57e-02 9.22e-06 4.53e-02]]
[[997.17429304]]
[[0.65918672 0.71942739 2.         0.1238621  0.13065461 0.04532822]]
[[0.7705   0.8425   6.       0.0254   0.149919 0.05115 ]]
[[963.0289685]]
[[0.84930769 0.48258077 9.         0.13335411 0.26677545 0.08112692]]
[[0.7705   0.8425   6.       0.0254   0.149919 0.05115 ]]
[[995.76197853]]
[[0.66637113 0.6502701  7.         0.220512   0.03572722 0.04817784]]
[[0.7705   0.8425   6.       0.0254   0.149919 0.05115 ]]
[[997.84822808]]
[[6.26e-01 6.55e-01 1.10e+01 2.46e-02 6.08e-03 1.02e-01]]
[[0.7705   0.8425   6.       0.0254   0.149919 0.05115 ]]
[[994.11122755]]
[[0.52584615 0.66461538 8.         0.47897608 0.21705387 0.05142308]]
[[0.7705   0.842

[[195.09342541]]
[[0.54973933 0.624882   1.         0.19907555 0.06265852 0.07452233]
 [0.54973933 0.624882   1.         0.19907555 0.06265852 0.07452233]
 [0.54973933 0.624882   1.         0.19907555 0.06265852 0.07452233]]
[[0.57081333 0.43770667 4.         0.37959733 0.00712678 0.10803467]]
[[866.83399452]
 [866.83399452]
 [866.83399452]]
[[ 0.62855814  0.5981938  11.          0.20131359  0.01354304  0.12008295]]
[[0.57081333 0.43770667 4.         0.37959733 0.00712678 0.10803467]]
[[992.1054978]]
[[0.3314846  0.45450404 9.         0.77993828 0.03847298 0.05817575]]
[[0.57081333 0.43770667 4.         0.37959733 0.00712678 0.10803467]]
[[992.71946607]]
[[3.9375e-01 7.2350e-01 5.0000e+00 5.0425e-01 4.3500e-05 3.2175e-02]]
[[0.57081333 0.43770667 4.         0.37959733 0.00712678 0.10803467]]
[[997.2152386]]
[[3.7560e-01 4.5440e-01 0.0000e+00 5.1360e-01 1.8842e-04 4.4540e-02]]
[[0.57081333 0.43770667 4.         0.37959733 0.00712678 0.10803467]]
[[191.71336257]]
[[0.52565635 0.61599448 

[[0.62570818 0.41430727 9.         0.13717733 0.15275976 0.05171273]]
[[0.88371895 0.43481699 8.         0.05221668 0.09913453 0.09357386]]
[[999.07956929]]
[[0.61428276 0.27323448 9.         0.13341454 0.59563442 0.09636035]
 [0.61428276 0.27323448 9.         0.13341454 0.59563442 0.09636035]]
[[0.88371895 0.43481699 8.         0.05221668 0.09913453 0.09357386]]
[[997.37684159]
 [997.37684159]]
[[0.75353243 0.39114595 9.         0.12310893 0.09206114 0.07187027]]
[[0.88371895 0.43481699 8.         0.05221668 0.09913453 0.09357386]]
[[999.5586599]]
[[0.83747945 0.3432274  9.         0.0147341  0.11290967 0.08888219]]
[[0.88371895 0.43481699 8.         0.05221668 0.09913453 0.09357386]]
[[999.71029572]]
[[0.84380263 0.4866579  7.         0.05491091 0.02484145 0.14635132]]
[[0.88371895 0.43481699 8.         0.05221668 0.09913453 0.09357386]]
[[999.75839155]]
[[0.47793205 0.5519337  7.         0.56256679 0.03421143 0.06453489]]
[[0.64517778 0.62553111 9.         0.20263058 0.03943353 0.11

[[0.25231651 0.51301476 5.         0.86106711 0.62578566 0.04170805]]
[[0.37682791 0.32215814 9.         0.65550698 0.32616722 0.04279767]]
[[989.47711946]]
[[0.35418919 0.39710811 5.         0.74389189 0.53602316 0.04858919]]
[[0.37682791 0.32215814 9.         0.65550698 0.32616722 0.04279767]]
[[993.54273651]]
[[ 0.76475     0.627125   11.          0.0195425   0.14662875  0.057225  ]]
[[0.73371429 0.33257143 0.         0.00853    0.68731571 0.03264286]]
[[74.55615077]]
[[9.25e-01 4.36e-01 2.00e+00 2.41e-04 8.50e-01 3.98e-02]]
[[0.73371429 0.33257143 0.         0.00853    0.68731571 0.03264286]]
[[553.73813548]]
[[0.72286517 0.38778764 7.         0.14227474 0.05711319 0.04802921]]
[[7.755000e-01 4.617500e-01 7.000000e+00 7.854600e-02 1.293303e-03
  3.197500e-02]]
[[999.84325138]]
[[7.73333333e-01 7.10000000e-01 0.00000000e+00 1.68833333e-01
  6.86000000e-06 3.60000000e-02]]
[[7.755000e-01 4.617500e-01 7.000000e+00 7.854600e-02 1.293303e-03
  3.197500e-02]]
[[125.43445712]]
[[0.61325  

[[0.59211111 0.72977778 1.         0.33671111 0.03392631 0.09863333]]
[[4.06333333e-01 6.28333333e-01 1.10000000e+01 1.92833333e-01
  8.23433000e-04 1.10166667e-01]]
[[753.62716737]]
[[0.30999699 0.56434171 5.         0.74532764 0.09099482 0.07483568]]
[[0.42316667 0.54166667 5.         0.60216667 0.12562767 0.04571667]]
[[999.31133115]]
[[2.205e-01 6.230e-01 7.000e+00 7.455e-01 1.750e-03 5.575e-02]]
[[0.42316667 0.54166667 5.         0.60216667 0.12562767 0.04571667]]
[[998.07003272]]
[[ 0.34317255  0.63847059 10.          0.67696601  0.03445869  0.0877268 ]]
[[0.42316667 0.54166667 5.         0.60216667 0.12562767 0.04571667]]
[[996.27238405]]
[[0.379125   0.46920833 4.         0.69656667 0.0763754  0.04599167]]
[[0.42316667 0.54166667 5.         0.60216667 0.12562767 0.04571667]]
[[998.55366995]]
[[5.59500e-01 6.10000e-01 6.00000e+00 3.27500e-01 3.91705e-04 3.44500e-02]]
[[3.2680e-01 2.9420e-01 7.0000e+00 6.8336e-01 2.4100e-06 1.0992e-01]]
[[996.23747533]]
[[3.99770961e-01 5.7392229

[[0.6311844  0.74788652 0.         0.10305848 0.0786573  0.04462128]]
[[ 0.61804167  0.60941667 10.          0.08402158  0.12688008  0.10277083]]
[[87.6040176]]
[[0.74978571 0.70314286 9.         0.03418571 0.11570141 0.04269286]]
[[ 0.61804167  0.60941667 10.          0.08402158  0.12688008  0.10277083]]
[[999.60293702]]
[[8.04433333e-01 8.43233333e-01 7.00000000e+00 1.65332333e-01
  2.21697800e-03 5.66800000e-02]]
[[ 0.61804167  0.60941667 10.          0.08402158  0.12688008  0.10277083]]
[[996.73381736]]
[[0.62563207 0.67911321 4.         0.35116981 0.0245384  0.05873208]]
[[ 0.61804167  0.60941667 10.          0.08402158  0.12688008  0.10277083]]
[[987.20196346]]
[[0.54054286 0.66593714 5.         0.27526857 0.00615598 0.04960571]]
[[ 0.61804167  0.60941667 10.          0.08402158  0.12688008  0.10277083]]
[[995.3330102]]
[[7.25527778e-01 8.18555556e-01 5.00000000e+00 1.29383333e-01
  4.12997800e-03 7.52750000e-02]]
[[ 0.61804167  0.60941667 10.          0.08402158  0.12688008  0.1

  1.16654800e-03 3.01974030e-02]]
[[4.4125e-01 6.4800e-01 2.0000e+00 2.0000e-01 3.0500e-05 3.0800e-02]]
[[961.32662744]]
[[0.64096154 0.78511538 0.         0.31063077 0.07202866 0.07391154]]
[[ 0.7625      0.82216667 10.          0.3445      0.05805665  0.04921667]]
[[116.47268185]]
[[ 0.55366667  0.87622222 10.          0.46277778  0.49485433  0.03853333]]
[[ 0.7625      0.82216667 10.          0.3445      0.05805665  0.04921667]]
[[998.76120715]]
[[0.63188   0.74376   2.        0.502452  0.0611265 0.077836 ]]
[[ 0.7625      0.82216667 10.          0.3445      0.05805665  0.04921667]]
[[925.2299786]]
[[0.57514078 0.71813107 0.         0.39750777 0.08310238 0.11140146]]
[[ 0.7625      0.82216667 10.          0.3445      0.05805665  0.04921667]]
[[115.4500052]]
[[4.045000e-01 6.091000e-01 7.000000e+00 5.327000e-01 2.278428e-03
  4.213000e-02]]
[[ 0.7625      0.82216667 10.          0.3445      0.05805665  0.04921667]]
[[998.95210607]]
[[3.3469375e-01 7.0150000e-01 8.0000000e+00 3.683125

[[936.37197333]]
[[7.720e-01 6.545e-01 7.000e+00 6.920e-04 3.509e-01 4.455e-02]]
[[9.18454545e-01 4.21636364e-01 2.00000000e+00 1.63045500e-03
  1.52000000e-05 1.21345455e-01]]
[[943.26787269]]
[[0.914  0.173  3.     0.0457 0.469  0.058 ]]
[[8.01e-01 7.58e-01 4.00e+00 4.23e-03 9.99e-06 3.34e-02]]
[[976.0650151]]
[[0.68015432 0.43948537 8.         0.12351189 0.12839654 0.04554789]]
[[8.01e-01 7.58e-01 4.00e+00 4.23e-03 9.99e-06 3.34e-02]]
[[985.21696214]]
[[8.60631579e-01 4.52631579e-01 6.00000000e+00 4.68368000e-04
  1.64242789e-01 7.32842110e-02]]
[[8.01e-01 7.58e-01 4.00e+00 4.23e-03 9.99e-06 3.34e-02]]
[[992.1843952]]
[[0.8145     0.303675   9.         0.01013275 0.01653125 0.045975  ]]
[[8.01e-01 7.58e-01 4.00e+00 4.23e-03 9.99e-06 3.34e-02]]
[[983.08749091]]
[[0.73542424 0.456      9.         0.07036262 0.35955918 0.07075152]]
[[8.01e-01 7.58e-01 4.00e+00 4.23e-03 9.99e-06 3.34e-02]]
[[983.72446174]]
[[0.841    0.1845   2.       0.004265 0.357025 0.1096  ]]
[[8.01e-01 7.58e-01 4.0

[[ 0.75975    0.669     10.         0.1511375  0.         0.0341   ]]
[[ 0.6592  0.5324 10.      0.218   0.      0.0384]]
[[999.83617611]]
[[0.42676    0.32443091 9.         0.54670454 0.00944691 0.03278364]]
[[ 0.6592  0.5324 10.      0.218   0.      0.0384]]
[[998.93012847]]
[[0.6810625  0.7457625  9.         0.53914583 0.00984948 0.04049583]]
[[ 0.6592  0.5324 10.      0.218   0.      0.0384]]
[[998.81005857]]
[[0.81566928 0.40208383 9.         0.02219709 0.18414016 0.09375269]]
[[0.9644     0.456255   0.         0.00159287 0.08747892 0.085325  ]]
[[102.32362635]]
[[8.863750e-01 5.355000e-01 1.100000e+01 2.141988e-03 8.120761e-03
  7.567500e-02]]
[[0.9644     0.456255   0.         0.00159287 0.08747892 0.085325  ]]
[[93.24228762]]
[[8.24071429e-01 2.42285714e-01 7.00000000e+00 5.86650000e-04
  2.16455286e-01 7.15142860e-02]]
[[0.9644     0.456255   0.         0.00159287 0.08747892 0.085325  ]]
[[122.7761061]]
[[0.82357576 0.47581818 0.         0.0446024  0.27867738 0.05017879]]
[[0.

[[0.51783115 0.62983392 9.         0.43785782 0.13428265 0.04529201]]
[[0.88088889 0.639      7.         0.01612889 0.00794099 0.0561    ]]
[[996.35280919]]
[[0.62006897 0.83593103 7.         0.09220483 0.18066272 0.06122069]]
[[0.71214286 0.61664286 0.         0.3234     0.17848657 0.04471429]]
[[142.49736069]]
[[6.13e-01 7.57e-01 0.00e+00 4.10e-01 1.01e-05 5.67e-02]]
[[0.71214286 0.61664286 0.         0.3234     0.17848657 0.04471429]]
[[968.77004283]]
[[0.56325    0.478875   0.         0.13023495 0.29670097 0.0464125 ]]
[[0.71214286 0.61664286 0.         0.3234     0.17848657 0.04471429]]
[[969.04590509]]
[[0.48201    0.62503    9.         0.362749   0.17373352 0.04362   ]]
[[0.71214286 0.61664286 0.         0.3234     0.17848657 0.04471429]]
[[95.95871875]]
[[4.51452911e-01 6.02015190e-01 7.00000000e+00 6.99296203e-01
  2.55808000e-04 6.21017720e-02]]
[[0.71214286 0.61664286 0.         0.3234     0.17848657 0.04471429]]
[[128.62021497]]
[[0.55729336 0.64976458 0.         0.42324421

[[0.47793205 0.5519337  7.         0.56256679 0.03421143 0.06453489]]
[[0.52351456 0.70996116 2.         0.31531767 0.02005603 0.04181845]]
[[950.34487452]]
[[2.81222222e-01 5.62444444e-01 5.00000000e+00 6.79777778e-01
  2.30111100e-03 1.00511111e-01]]
[[0.52351456 0.70996116 2.         0.31531767 0.02005603 0.04181845]]
[[958.17531619]]
[[0.429547   0.6180575  5.         0.797565   0.18211839 0.0780215 ]]
[[0.52351456 0.70996116 2.         0.31531767 0.02005603 0.04181845]]
[[965.1873315]]
[[0.64560526 0.59782895 0.         0.24712658 0.38892699 0.06133947]]
[[0.52351456 0.70996116 2.         0.31531767 0.02005603 0.04181845]]
[[386.99039044]]
[[0.40222083 0.56454167 5.         0.80341875 0.27467521 0.03995417]]
[[0.52351456 0.70996116 2.         0.31531767 0.02005603 0.04181845]]
[[961.46414845]]
[[0.30053    0.44124    7.         0.54885    0.44933071 0.04484167]]
[[0.52351456 0.70996116 2.         0.31531767 0.02005603 0.04181845]]
[[940.16594519]]
[[0.63394444 0.76938889 7.       

[[961.88925692]]
[[0.32358    0.4795     0.         0.74428    0.43948887 0.070012  ]]
[[0.56855556 0.62224444 2.         0.28593486 0.05968338 0.05256444]]
[[317.52833202]]
[[0.57978626 0.66227939 2.         0.33432829 0.05913408 0.03778244]]
[[0.56855556 0.62224444 2.         0.28593486 0.05968338 0.05256444]]
[[999.60328858]]
[[0.66878261 0.6666413  5.         0.33425228 0.06420809 0.04311522]]
[[0.56855556 0.62224444 2.         0.28593486 0.05968338 0.05256444]]
[[975.38711022]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]]
[[0.56855556 0.62224444 2.         0.28593486 0.05968338 0.05256444]]
[[406.43211726]]
[[0.7625     0.64376923 7.         0.22002791 0.01629055 0.05579615]]
[[0.56855556 0.62224444 2.         0.28593486 0.05968338 0.05256444]]
[[961.54016908]]
[[0.66808814 0.6425     0.         0.22149347 0.05059403 0.04797542]
 [0.66808814 0.6425     0.         0.22149347 0.05059403 0.04797542]]
[[7.78076923e-01 6.56384615e-01 1.00000000e+00 1.76438462e-

[[ 0.65195238  0.5984619  11.          0.03889169  0.1769661   0.05026984]]
[[0.69844444 0.36811111 8.         0.10989    0.03314889 0.04723333]]
[[999.45335724]]
[[8.935e-01 4.265e-01 8.000e+00 1.085e-04 6.085e-01 9.450e-02]]
[[0.69844444 0.36811111 8.         0.10989    0.03314889 0.04723333]]
[[997.04011996]]
[[0.55875    0.79125    2.         0.375157   0.11971554 0.10262   ]]
[[0.626  0.96   8.     0.182  0.873  0.0399]]
[[941.05733812]]
[[0.64145454 0.67363636 9.         0.23225182 0.43319691 0.06239091]]
[[0.626  0.96   8.     0.182  0.873  0.0399]]
[[997.20029989]]
[[3.320e-01 5.830e-01 7.000e+00 1.965e-01 2.640e-03 4.915e-02]]
[[0.626  0.96   8.     0.182  0.873  0.0399]]
[[993.13341049]]
[[0.43586667 0.59133333 5.         0.7155     0.63940042 0.04797708]]
[[0.626  0.96   8.     0.182  0.873  0.0399]]
[[992.93087669]]
[[0.39263333 0.13377778 2.         0.77255556 0.80644444 0.06658889]]
[[0.121  0.2476 7.     0.891  0.9195 0.0358]]
[[935.34186359]]
[[0.22825  0.076975 4.     

[[0.2834     0.467125   7.         0.712125   0.05073464 0.054125  ]]
[[3.824000e-01 4.034000e-01 1.100000e+01 4.870000e-01 5.402416e-03
  3.430000e-02]]
[[997.88770819]]
[[1.33466667e-01 4.30000000e-01 1.10000000e+01 6.95666667e-01
  3.00000000e-04 3.47666670e-02]]
[[3.824000e-01 4.034000e-01 1.100000e+01 4.870000e-01 5.402416e-03
  3.430000e-02]]
[[999.56337402]]
[[0.61754546 0.68569697 7.         0.28302545 0.00878001 0.03440909]]
[[3.824000e-01 4.034000e-01 1.100000e+01 4.870000e-01 5.402416e-03
  3.430000e-02]]
[[996.74827789]]
[[0.46560426 0.68208936 5.         0.47685957 0.02557615 0.04021383]]
[[3.824000e-01 4.034000e-01 1.100000e+01 4.870000e-01 5.402416e-03
  3.430000e-02]]
[[992.27662354]]
[[0.23866667 0.42966667 3.         0.91533333 0.00578377 0.0307    ]]
[[3.824000e-01 4.034000e-01 1.100000e+01 4.870000e-01 5.402416e-03
  3.430000e-02]]
[[963.08820089]]
[[6.50198198e-01 5.17234234e-01 9.00000000e+00 2.09684865e-01
  8.80334700e-03 3.67270270e-02]]
[[3.824000e-01 4.034000

[[0.51235915 0.46570423 7.         0.38138028 0.01767355 0.03712746]]
[[7.6500000e-01 5.5300000e-01 7.0000000e+00 2.7333333e-02 2.3966670e-03
  5.0233333e-02]]
[[998.02209472]]
[[0.57433775 0.5413949  4.         0.34633785 0.09784331 0.03524286]]
[[7.6500000e-01 5.5300000e-01 7.0000000e+00 2.7333333e-02 2.3966670e-03
  5.0233333e-02]]
[[994.39738977]]
[[0.39708878 0.4946415  7.         0.46080888 0.04617556 0.03768605]]
[[7.6500000e-01 5.5300000e-01 7.0000000e+00 2.7333333e-02 2.3966670e-03
  5.0233333e-02]]
[[996.700338]]
[[0.34086429 0.50970519 0.         0.54829545 0.01488308 0.03978831]
 [0.34086429 0.50970519 0.         0.54829545 0.01488308 0.03978831]]
[[7.6500000e-01 5.5300000e-01 7.0000000e+00 2.7333333e-02 2.3966670e-03
  5.0233333e-02]]
[[96.1924498]
 [96.1924498]]
[[0.57978626 0.66227939 2.         0.33432829 0.05913408 0.03778244]]
[[7.6500000e-01 5.5300000e-01 7.0000000e+00 2.7333333e-02 2.3966670e-03
  5.0233333e-02]]
[[948.70494195]]
[[4.72e-01 2.54e-01 1.00e+00 3.70e-0

[[0.30303143 0.25893429 4.         0.3425954  0.2821047  0.04579143]]
[[ 0.58525   0.38525  11.        0.436425  0.75725   0.03225 ]]
[[998.2560386]]
[[0.57950541 0.38014595 2.         0.16597181 0.11997386 0.04218108]]
[[ 0.58525   0.38525  11.        0.436425  0.75725   0.03225 ]]
[[963.10609876]]
[[0.22825  0.076975 4.       0.79     0.773    0.0395  ]]
[[ 0.58525   0.38525  11.        0.436425  0.75725   0.03225 ]]
[[981.07673559]]
[[0.85727225 0.55270733 1.         0.17069092 0.0735082  0.08195393]]
[[ 0.58525   0.38525  11.        0.436425  0.75725   0.03225 ]]
[[742.65224996]]
[[0.6888432  0.50598757 2.         0.22353723 0.15842088 0.06207041]]
[[ 0.58525   0.38525  11.        0.436425  0.75725   0.03225 ]]
[[940.99546713]]
[[0.55951667 0.30672917 4.         0.21167042 0.40019283 0.04379167]]
[[ 0.58525   0.38525  11.        0.436425  0.75725   0.03225 ]]
[[994.98662211]]
[[0.56474667 0.37555697 7.         0.25449917 0.10525787 0.04692   ]]
[[ 0.58525   0.38525  11.        0.43

  1.16654800e-03 3.01974030e-02]]
[[6.29241379e-01 5.44057471e-01 7.00000000e+00 2.47734483e-01
  3.39236000e-04 3.18735630e-02]]
[[999.36442382]]
[[4.35087234e-01 5.45989362e-01 2.00000000e+00 3.09263830e-01
  1.69811000e-04 3.25861700e-02]]
[[6.29241379e-01 5.44057471e-01 7.00000000e+00 2.47734483e-01
  3.39236000e-04 3.18735630e-02]]
[[969.95032552]]
[[0.41247059 0.61450267 2.         0.51584064 0.01694326 0.04372941]]
[[6.29241379e-01 5.44057471e-01 7.00000000e+00 2.47734483e-01
  3.39236000e-04 3.18735630e-02]]
[[951.12530097]]
[[4.48006329e-01 6.18436709e-01 7.00000000e+00 4.28697468e-01
  3.13137000e-04 4.98050630e-02]]
[[6.29241379e-01 5.44057471e-01 7.00000000e+00 2.47734483e-01
  3.39236000e-04 3.18735630e-02]]
[[999.2821171]]
[[0.4376 0.733  7.     0.4288 0.     0.137 ]]
[[6.29241379e-01 5.44057471e-01 7.00000000e+00 2.47734483e-01
  3.39236000e-04 3.18735630e-02]]
[[998.83529006]]
[[4.74728070e-01 5.43385965e-01 7.00000000e+00 4.01884737e-01
  6.33441000e-03 4.06938600e-02]

[[0.907625   0.5435     5.         0.0130466  0.06693929 0.0673    ]]
[[0.892125   0.4605625  1.         0.02633588 0.0327823  0.07154375]]
[[836.21811001]]
[[0.83493333 0.44686667 9.         0.03877489 0.06527629 0.07669333]]
[[0.892125   0.4605625  1.         0.02633588 0.0327823  0.07154375]]
[[775.24615056]]
[[7.5912500e-01 5.2787500e-01 2.0000000e+00 1.0143654e-02 1.4767820e-03
  6.4195833e-02]]
[[0.892125   0.4605625  1.         0.02633588 0.0327823  0.07154375]]
[[934.88641214]]
[[0.76389103 0.43876346 1.         0.10778508 0.10712546 0.06150256]
 [0.76389103 0.43876346 1.         0.10778508 0.10712546 0.06150256]]
[[0.892125   0.4605625  1.         0.02633588 0.0327823  0.07154375]]
[[993.88976573]
 [993.88976573]]
[[0.82357576 0.47581818 0.         0.0446024  0.27867738 0.05017879]]
[[0.892125   0.4605625  1.         0.02633588 0.0327823  0.07154375]]
[[686.31608322]]
[[0.90390756 0.33906177 4.         0.02006071 0.22803874 0.09990336]]
[[0.892125   0.4605625  1.         0.026

[[0.51337736 0.45058113 9.         0.11469208 0.44210362 0.06929245]]
[[2.95e-01 9.06e-02 1.10e+01 6.54e-01 5.57e-05 3.26e-02]]
[[996.38507067]]
[[0.30053    0.44124    7.         0.54885    0.44933071 0.04484167]]
[[2.95e-01 9.06e-02 1.10e+01 6.54e-01 5.57e-05 3.26e-02]]
[[996.17959188]]
[[0.33283666 0.12462835 2.         0.81143402 0.74199736 0.04936031]]
[[2.95e-01 9.06e-02 1.10e+01 6.54e-01 5.57e-05 3.26e-02]]
[[888.9995767]]
[[0.545   0.631   2.      0.904   0.00667 0.138  ]]
[[0.63374468 0.75331915 2.         0.47692766 0.07844795 0.0472383 ]]
[[980.09113742]]
[[0.49147668 0.61614508 2.         0.62601969 0.03534392 0.06881969]]
[[0.63374468 0.75331915 2.         0.47692766 0.07844795 0.0472383 ]]
[[993.94279197]]
[[0.23636 0.6194  7.      0.9322  0.7964  0.0609 ]]
[[0.41525    0.46858333 5.         0.542225   0.39593729 0.1734    ]]
[[997.62216436]]
[[0.19762941 0.43177647 7.         0.87907059 0.29797655 0.05547765]]
[[0.41525    0.46858333 5.         0.542225   0.39593729 0.17

[[990.55900571]]
[[0.57514078 0.71813107 0.         0.39750777 0.08310238 0.11140146]]
[[5.19666667e-01 7.91000000e-01 1.00000000e+01 2.14333333e-01
  2.36000000e-06 5.74000000e-02]]
[[94.2853022]]
[[4.51452911e-01 6.02015190e-01 7.00000000e+00 6.99296203e-01
  2.55808000e-04 6.21017720e-02]]
[[5.19666667e-01 7.91000000e-01 1.00000000e+01 2.14333333e-01
  2.36000000e-06 5.74000000e-02]]
[[996.88095436]]
[[0.55729336 0.64976458 0.         0.42324421 0.13706214 0.04991384]]
[[5.19666667e-01 7.91000000e-01 1.00000000e+01 2.14333333e-01
  2.36000000e-06 5.74000000e-02]]
[[92.43574411]]
[[0.54973933 0.624882   1.         0.19907555 0.06265852 0.07452233]
 [0.54973933 0.624882   1.         0.19907555 0.06265852 0.07452233]
 [0.54973933 0.624882   1.         0.19907555 0.06265852 0.07452233]]
[[5.19666667e-01 7.91000000e-01 1.00000000e+01 2.14333333e-01
  2.36000000e-06 5.74000000e-02]]
[[816.51245289]
 [816.51245289]
 [816.51245289]]
[[0.39617253 0.62595864 9.         0.44230364 0.01453375 0

  6.65963300e-03 5.00657890e-02]]
[[6.49921053e-01 5.40244737e-01 9.00000000e+00 3.39639474e-01
  9.62403000e-04 5.68210530e-02]]
[[999.49750272]]
[[0.62563207 0.67911321 4.         0.35116981 0.0245384  0.05873208]]
[[6.49921053e-01 5.40244737e-01 9.00000000e+00 3.39639474e-01
  9.62403000e-04 5.68210530e-02]]
[[989.80212677]]
[[0.51694915 0.59991525 0.         0.50087797 0.01626139 0.04800678]]
[[6.49921053e-01 5.40244737e-01 9.00000000e+00 3.39639474e-01
  9.62403000e-04 5.68210530e-02]]
[[98.12148341]]
[[ 0.722   0.62   11.      0.522   0.      0.0388]]
[[6.49921053e-01 5.40244737e-01 9.00000000e+00 3.39639474e-01
  9.62403000e-04 5.68210530e-02]]
[[999.92138715]]
[[0.43123502 0.57380691 0.         0.60436968 0.00593847 0.06027558]]
[[6.49921053e-01 5.40244737e-01 9.00000000e+00 3.39639474e-01
  9.62403000e-04 5.68210530e-02]]
[[93.92911932]]
[[0.3852  0.29198 4.      0.447   0.5932  0.0321 ]]
[[ 0.7       0.8468   11.        0.05377   0.538838  0.0645  ]]
[[989.3058262]]
[[0.91456

[[2.94128571e-01 4.93485714e-01 9.00000000e+00 7.24814286e-01
  1.12949600e-03 3.22171430e-02]]
[[4.8000e-01 5.9940e-01 1.1000e+01 3.5036e-01 5.3033e-04 3.4480e-02]]
[[998.76761906]]
[[ 0.38409351  0.51935714 10.          0.54069481  0.01119366  0.03593377]]
[[4.8000e-01 5.9940e-01 1.1000e+01 3.5036e-01 5.3033e-04 3.4480e-02]]
[[999.73745341]]
[[0.4114408  0.578124   2.         0.6101024  0.00657685 0.043718  ]]
[[4.8000e-01 5.9940e-01 1.1000e+01 3.5036e-01 5.3033e-04 3.4480e-02]]
[[934.07536311]]
[[0.502   0.9405  4.      0.601   0.      0.04335]]
[[4.8000e-01 5.9940e-01 1.1000e+01 3.5036e-01 5.3033e-04 3.4480e-02]]
[[975.41683254]]
[[4.35353425e-01 7.27767123e-01 1.00000000e+00 6.76598630e-01
  9.87824000e-04 4.24369860e-02]]
[[4.8000e-01 5.9940e-01 1.1000e+01 3.5036e-01 5.3033e-04 3.4480e-02]]
[[729.75527737]]
[[4.47153846e-01 6.47307692e-01 7.00000000e+00 4.87523077e-01
  2.33000000e-05 3.68000000e-02]]
[[4.8000e-01 5.9940e-01 1.1000e+01 3.5036e-01 5.3033e-04 3.4480e-02]]
[[998.392

[[0.59235659 0.57925892 2.         0.42715814 0.12266223 0.06221783]]
[[0.614      0.605      9.         0.16512106 0.15362869 0.04158235]]
[[940.53978402]]
[[0.877   0.7545  7.      0.07153 0.01935 0.07805]]
[[0.614      0.605      9.         0.16512106 0.15362869 0.04158235]]
[[997.47809786]]
[[0.5125     0.60457143 9.         0.37557143 0.45958831 0.04536429]]
[[0.614      0.605      9.         0.16512106 0.15362869 0.04158235]]
[[999.09566144]]
[[0.71646075 0.53921028 8.         0.21113931 0.17333124 0.09865981]]
[[0.614      0.605      9.         0.16512106 0.15362869 0.04158235]]
[[999.7052439]]
[[3.52666667e-01 5.05000000e-01 5.00000000e+00 4.33066667e-01
  2.64000000e-05 3.58666670e-02]]
[[0.614      0.605      9.         0.16512106 0.15362869 0.04158235]]
[[997.01682313]]
[[0.39708878 0.4946415  7.         0.46080888 0.04617556 0.03768605]]
[[0.614      0.605      9.         0.16512106 0.15362869 0.04158235]]
[[998.76042483]]
[[0.923  0.681  2.     0.0108 0.436  0.123 ]]
[[0.6

[[395.45530936]]
[[4.51452911e-01 6.02015190e-01 7.00000000e+00 6.99296203e-01
  2.55808000e-04 6.21017720e-02]]
[[0.53967677 0.6140404  2.         0.3674105  0.0040544  0.05451717]]
[[958.89418019]]
[[0.55729336 0.64976458 0.         0.42324421 0.13706214 0.04991384]]
[[0.53967677 0.6140404  2.         0.3674105  0.0040544  0.05451717]]
[[405.38090746]]
[[3.2600e-01 5.0100e-01 1.1000e+01 2.9005e-01 1.1600e-05 6.3500e-02]]
[[0.53967677 0.6140404  2.         0.3674105  0.0040544  0.05451717]]
[[935.16976881]]
[[0.41247742 0.66565161 0.         0.33180129 0.03368859 0.05191484]]
[[0.53967677 0.6140404  2.         0.3674105  0.0040544  0.05451717]]
[[404.50949898]]
[[0.51694915 0.59991525 0.         0.50087797 0.01626139 0.04800678]]
[[0.53967677 0.6140404  2.         0.3674105  0.0040544  0.05451717]]
[[405.42674565]]
[[2.72969697e-01 4.58090909e-01 1.10000000e+01 4.49633333e-01
  7.69663800e-03 3.20696970e-02]]
[[0.53967677 0.6140404  2.         0.3674105  0.0040544  0.05451717]]
[[935.

  1.65000000e-06 3.63505150e-02]]
[[0.205   0.173   9.      0.876   0.      0.04795]]
[[961.82364507]]
[[0.41247742 0.66565161 0.         0.33180129 0.03368859 0.05191484]]
[[0.205   0.173   9.      0.876   0.      0.04795]]
[[63.88904385]]
[[0.23801673 0.36428824 5.         0.73564823 0.02085498 0.04961424]]
[[0.205   0.173   9.      0.876   0.      0.04795]]
[[997.09593193]]
[[0.4514021  0.68665263 0.         0.57210779 0.00079834 0.05763053]]
[[0.205   0.173   9.      0.876   0.      0.04795]]
[[78.83181511]]
[[3.11571429e-01 2.39300000e-01 4.00000000e+00 5.94757143e-01
  5.49000000e-05 3.21571430e-02]]
[[0.205   0.173   9.      0.876   0.      0.04795]]
[[996.46509865]]
[[0.6810625  0.7457625  9.         0.53914583 0.00984948 0.04049583]]
[[0.205   0.173   9.      0.876   0.      0.04795]]
[[995.93282463]]
[[0.43123502 0.57380691 0.         0.60436968 0.00593847 0.06027558]]
[[0.205   0.173   9.      0.876   0.      0.04795]]
[[84.64015767]]
[[3.61913043e-01 5.65695652e-01 8.000000

[[0.64440741 0.48776543 9.         0.18209259 0.05570974 0.05975062]]
[[7.94166667e-01 3.55333333e-01 6.00000000e+00 7.78121670e-02
  3.46700000e-04 8.38166670e-02]]
[[998.11784151]]
[[8.82e-01 3.98e-01 7.00e+00 2.54e-03 2.17e-05 3.62e-02]]
[[7.94166667e-01 3.55333333e-01 6.00000000e+00 7.78121670e-02
  3.46700000e-04 8.38166670e-02]]
[[999.862228]]
[[0.580796   0.70601    1.         0.461112   0.02289749 0.057821  ]]
[[7.94166667e-01 3.55333333e-01 6.00000000e+00 7.78121670e-02
  3.46700000e-04 8.38166670e-02]]
[[777.36208367]]
[[6.270e-01 7.325e-01 9.000e+00 2.725e-01 8.011e-03 4.765e-02]]
[[7.94166667e-01 3.55333333e-01 6.00000000e+00 7.78121670e-02
  3.46700000e-04 8.38166670e-02]]
[[997.65082342]]
[[0.6888432  0.50598757 2.         0.22353723 0.15842088 0.06207041]]
[[7.94166667e-01 3.55333333e-01 6.00000000e+00 7.78121670e-02
  3.46700000e-04 8.38166670e-02]]
[[958.73498037]]
[[0.64683333 0.88266667 9.         0.31585    0.45963333 0.07126667]]
[[7.94166667e-01 3.55333333e-01 6.0

[[ 0.80964286  0.80542857 11.          0.02427943  0.12419728  0.048     ]]
[[6.82105263e-01 6.76315789e-01 8.00000000e+00 1.56520000e-01
  3.91956400e-03 4.63052630e-02]]
[[999.66419095]]
[[0.65821053 0.48276316 9.         0.13090768 0.0985612  0.04482632]]
[[6.82105263e-01 6.76315789e-01 8.00000000e+00 1.56520000e-01
  3.91956400e-03 4.63052630e-02]]
[[999.39335332]]
[[0.94866667 0.57733333 6.         0.31986667 0.42633333 0.05773333]]
[[6.82105263e-01 6.76315789e-01 8.00000000e+00 1.56520000e-01
  3.91956400e-03 4.63052630e-02]]
[[994.46071203]]
[[4.27238095e-01 4.60666667e-01 1.10000000e+01 6.73652381e-01
  5.46523200e-03 4.35571430e-02]]
[[6.82105263e-01 6.76315789e-01 8.00000000e+00 1.56520000e-01
  3.91956400e-03 4.63052630e-02]]
[[997.18067711]]
[[0.42676    0.32443091 9.         0.54670454 0.00944691 0.03278364]]
[[6.82105263e-01 6.76315789e-01 8.00000000e+00 1.56520000e-01
  3.91956400e-03 4.63052630e-02]]
[[997.29475351]]
[[3.11571429e-01 2.39300000e-01 4.00000000e+00 5.9475

[[0.30882146 0.45413242 0.         0.55090984 0.00886569 0.03567808]]
[[8.11142857e-01 7.53857143e-01 2.00000000e+00 1.21428571e-01
  1.16000000e-05 4.38142860e-02]]
[[370.86568064]]
[[0.58600845 0.53085    0.         0.35095862 0.01154242 0.04238081]]
[[8.11142857e-01 7.53857143e-01 2.00000000e+00 1.21428571e-01
  1.16000000e-05 4.38142860e-02]]
[[463.85143444]]
[[0.31550732 0.47122439 0.         0.50159024 0.00943807 0.03537317]]
[[3.25100000e-01 3.01844444e-01 1.10000000e+01 7.13666667e-01
  2.60828300e-03 3.16333330e-02]]
[[72.22119921]]
[[ 0.38409351  0.51935714 10.          0.54069481  0.01119366  0.03593377]]
[[3.25100000e-01 3.01844444e-01 1.10000000e+01 7.13666667e-01
  2.60828300e-03 3.16333330e-02]]
[[999.60447976]]
[[0.34341429 0.43555714 0.         0.56017589 0.03042517 0.03070804]]
[[3.25100000e-01 3.01844444e-01 1.10000000e+01 7.13666667e-01
  2.60828300e-03 3.16333330e-02]]
[[73.93301739]]
[[0.28882121 0.43384849 7.         0.71924242 0.0274342  0.0373    ]]
[[3.2510000

[[4.30e-01 7.16e-01 2.00e+00 3.12e-02 1.89e-04 6.80e-02]]
[[6.60454545e-01 7.34393939e-01 6.00000000e+00 7.36573940e-02
  1.18000000e-05 1.54309091e-01]]
[[971.97050182]]
[[0.54070588 0.74476471 9.         0.27805882 0.02666079 0.09780588]]
[[6.60454545e-01 7.34393939e-01 6.00000000e+00 7.36573940e-02
  1.18000000e-05 1.54309091e-01]]
[[997.75328216]]
[[0.52892308 0.79738462 9.         0.19943272 0.06076997 0.0805    ]]
[[6.60454545e-01 7.34393939e-01 6.00000000e+00 7.36573940e-02
  1.18000000e-05 1.54309091e-01]]
[[997.97194093]]
[[0.53732877 0.81180822 1.         0.21676301 0.00197604 0.06426164]]
[[6.60454545e-01 7.34393939e-01 6.00000000e+00 7.36573940e-02
  1.18000000e-05 1.54309091e-01]]
[[811.23004832]]
[[0.63985455 0.82368182 7.         0.11665309 0.01426668 0.13464364]]
[[6.60454545e-01 7.34393939e-01 6.00000000e+00 7.36573940e-02
  1.18000000e-05 1.54309091e-01]]
[[999.79028682]]
[[0.43369231 0.74384615 1.         0.29167077 0.13649823 0.21374615]]
[[6.60454545e-01 7.34393939

 [644.19402578]]
[[0.3314846  0.45450404 9.         0.77993828 0.03847298 0.05817575]]
[[0.63083333 0.55633333 0.         0.22453833 0.18496888 0.13008333]]
[[80.05745805]]
[[0.70614706 0.88458823 0.         0.08232535 0.07880208 0.07082941]]
[[0.63083333 0.55633333 0.         0.22453833 0.18496888 0.13008333]]
[[955.78285826]]
[[0.33766042 0.45492797 0.         0.71042288 0.08813228 0.09591186]]
[[0.63083333 0.55633333 0.         0.22453833 0.18496888 0.13008333]]
[[792.57677672]]
[[0.78132653 0.42716531 7.         0.10958663 0.16073012 0.06293061]]
[[0.63083333 0.55633333 0.         0.22453833 0.18496888 0.13008333]]
[[124.89948908]]
[[0.60945454 0.77290909 7.         0.33107273 0.09534324 0.13114545]]
[[0.63083333 0.55633333 0.         0.22453833 0.18496888 0.13008333]]
[[145.04989306]]
[[0.35842027 0.46151081 1.         0.57107838 0.03837299 0.04333243]]
[[0.63083333 0.55633333 0.         0.22453833 0.18496888 0.13008333]]
[[536.54085561]]
[[0.57514078 0.71813107 0.         0.39750

[[0.35070175 0.36226316 0.         0.41886947 0.10484212 0.03534737]]
[[0.536      0.5372     2.         0.37466    0.00916614 0.04468   ]]
[[375.38768082]]
[[0.539125   0.4125     9.         0.31923475 0.343675   0.0558    ]]
[[0.536      0.5372     2.         0.37466    0.00916614 0.04468   ]]
[[949.26142142]]
[[0.46408    0.535716   9.         0.509736   0.11521679 0.038208  ]]
[[0.536      0.5372     2.         0.37466    0.00916614 0.04468   ]]
[[953.53047413]]
[[0.59526816 0.54763363 0.         0.25457736 0.07640244 0.0597657 ]]
[[0.536      0.5372     2.         0.37466    0.00916614 0.04468   ]]
[[384.04594205]]
[[0.50264286 0.55885714 2.         0.30118357 0.33812247 0.04167143]]
[[0.536      0.5372     2.         0.37466    0.00916614 0.04468   ]]
[[987.87645894]]
[[0.33766042 0.45492797 0.         0.71042288 0.08813228 0.09591186]]
[[0.536      0.5372     2.         0.37466    0.00916614 0.04468   ]]
[[349.37262751]]
[[0.23339565 0.667      7.         0.8463913  0.53140835 0

[[0.07980929 0.18695    5.         0.98507143 0.77621429 0.06614286]]
[[0.63858333 0.70458333 6.         0.14325424 0.41525058 0.04070833]]
[[975.30674531]]
[[0.42335897 0.62576923 7.         0.67953846 0.02069805 0.03555897]]
[[0.63858333 0.70458333 6.         0.14325424 0.41525058 0.04070833]]
[[993.84560512]]
[[0.912  0.667  9.     0.232  0.0497 0.0781]]
[[0.63858333 0.70458333 6.         0.14325424 0.41525058 0.04070833]]
[[997.10901262]]
[[0.31665217 0.35194783 5.         0.74732957 0.76990522 0.0411087 ]]
[[0.63858333 0.70458333 6.         0.14325424 0.41525058 0.04070833]]
[[987.10730591]]
[[0.37163005 0.45386943 7.         0.62164539 0.26691648 0.04929171]]
[[0.63858333 0.70458333 6.         0.14325424 0.41525058 0.04070833]]
[[994.75086587]]
[[0.76157143 0.39674286 9.         0.08073429 0.80342857 0.03678571]]
[[0.63858333 0.70458333 6.         0.14325424 0.41525058 0.04070833]]
[[996.85296008]]
[[0.70626667 0.49286667 9.         0.44382667 0.02545715 0.08584   ]]
[[0.63858333

[[0.8145     0.303675   9.         0.01013275 0.01653125 0.045975  ]]
[[0.2643125  0.241225   3.         0.8225625  0.02257126 0.037325  ]]
[[964.10041696]]
[[0.49760845 0.28911831 1.         0.28662822 0.06902765 0.0541507 ]]
[[0.2643125  0.241225   3.         0.8225625  0.02257126 0.037325  ]]
[[921.66286729]]
[[0.47793205 0.5519337  7.         0.56256679 0.03421143 0.06453489]]
[[ 0.3489      0.32575    11.          0.52083333  0.12004789  0.06385   ]]
[[997.59816066]]
[[0.6318764  0.71397753 1.         0.34312472 0.09316107 0.09830674]]
[[ 0.3489      0.32575    11.          0.52083333  0.12004789  0.06385   ]]
[[738.95612257]]
[[0.35616324 0.43265613 0.         0.68121652 0.1455987  0.0533081 ]]
[[ 0.3489      0.32575    11.          0.52083333  0.12004789  0.06385   ]]
[[64.91364057]]
[[ 0.14508621  0.32482759 10.          0.9182069   0.03162133  0.03913793]]
[[ 0.3489      0.32575    11.          0.52083333  0.12004789  0.06385   ]]
[[998.83888483]]
[[0.42698667 0.44490667 5.   

[[0.30053    0.44124    7.         0.54885    0.44933071 0.04484167]]
[[4.8412500e-01 5.4268750e-01 7.0000000e+00 5.1649375e-01 4.2276750e-03
  3.2756250e-02]]
[[997.55682525]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]]
[[4.8412500e-01 5.4268750e-01 7.0000000e+00 5.1649375e-01 4.2276750e-03
  3.2756250e-02]]
[[123.60931908]]
[[0.831  0.942  2.     0.0807 0.     0.0358]]
[[7.56e-01 3.32e-01 9.00e+00 9.79e-04 3.38e-04 3.07e-02]]
[[886.7983113]]
[[0.70796018 0.67552986 7.         0.29628701 0.02241103 0.05524434]]
[[7.56e-01 3.32e-01 9.00e+00 9.79e-04 3.38e-04 3.07e-02]]
[[997.23191712]]
[[4.5290e-01 4.7450e-01 1.0000e+00 6.6850e-01 6.7100e-05 1.2982e-01]]
[[0.567      0.79433333 6.         0.53216667 0.00959635 0.04451667]]
[[832.95076422]]
[[5.01355556e-01 7.38622222e-01 2.00000000e+00 4.33506667e-01
  7.93000000e-06 3.34022220e-02]]
[[0.605      0.56016667 2.         0.24748333 0.1612746  0.0402    ]]
[[989.66121364]]
[[6.515e-01 9.490e-01 3.000e+00 4.955e-01

[[7.13300e-01 5.70500e-01 9.00000e+00 2.75560e-01 6.06282e-04 5.67500e-02]]
[[0.415      0.513      4.         0.3316     0.01898    0.03413333]]
[[996.36293706]]
[[1.69171429e-01 5.18285714e-01 9.00000000e+00 8.19428571e-01
  6.89000000e-03 3.84285710e-02]]
[[0.415      0.513      4.         0.3316     0.01898    0.03413333]]
[[994.04204347]]
[[0.55194977 0.73186512 0.         0.42869907 0.02045842 0.04323395]]
[[0.415      0.513      4.         0.3316     0.01898    0.03413333]]
[[181.6361826]]
[[0.72382625 0.50383977 2.         0.22389196 0.06939168 0.06255116]]
[[0.415      0.513      4.         0.3316     0.01898    0.03413333]]
[[965.40768236]]
[[0.366515   0.41189    7.         0.5673745  0.04425532 0.037235  ]]
[[0.415      0.513      4.         0.3316     0.01898    0.03413333]]
[[996.40259518]]
[[0.35878571 0.6815     8.         0.82638095 0.43855031 0.04688175]]
[[0.415      0.513      4.         0.3316     0.01898    0.03413333]]
[[996.00224412]]
[[0.54682697 0.61965954 0. 

[[94.55670252]]
[[5.37714286e-01 8.55142857e-01 9.00000000e+00 4.01142857e-01
  2.01843000e-04 3.10857140e-02]]
[[0.49706832 0.57536646 9.         0.38843884 0.13590351 0.04700621]]
[[999.40105481]]
[[0.63188   0.74376   2.        0.502452  0.0611265 0.077836 ]]
[[0.52666667 0.822      7.         0.48833333 0.00928667 0.05176667]]
[[939.14700659]]
[[4.29000000e-01 8.67666667e-01 4.00000000e+00 2.59410000e-01
  1.74175000e-03 3.80333330e-02]]
[[0.52666667 0.822      7.         0.48833333 0.00928667 0.05176667]]
[[994.92191994]]
[[0.487188   0.6348     9.         0.251208   0.05815845 0.068872  ]]
[[0.52666667 0.822      7.         0.48833333 0.00928667 0.05176667]]
[[997.85415155]]
[[0.8455    0.8495    6.        0.098     0.0566485 0.1813   ]]
[[0.52666667 0.822      7.         0.48833333 0.00928667 0.05176667]]
[[995.99603795]]
[[0.48955556 0.62533333 5.         0.62988889 0.27992222 0.10181111]]
[[0.52666667 0.822      7.         0.48833333 0.00928667 0.05176667]]
[[996.71862316]]
[[

[[ 0.69322413  0.62539303 11.          0.25530043  0.04598462  0.06931046]]
[[6.49629630e-01 6.38851852e-01 6.00000000e+00 1.05440000e-01
  1.18176400e-03 5.55148150e-02]]
[[997.78161233]]
[[3.99058824e-01 5.23235294e-01 1.00000000e+01 2.06822353e-01
  2.22411000e-04 4.08411760e-02]]
[[6.49629630e-01 6.38851852e-01 6.00000000e+00 1.05440000e-01
  1.18176400e-03 5.55148150e-02]]
[[996.2740909]]
[[ 0.5769      0.67505    11.          0.0479905   0.04457448  0.05321   ]]
[[6.49629630e-01 6.38851852e-01 6.00000000e+00 1.05440000e-01
  1.18176400e-03 5.55148150e-02]]
[[997.39407748]]
[[0.54054286 0.66593714 5.         0.27526857 0.00615598 0.04960571]]
[[6.49629630e-01 6.38851852e-01 6.00000000e+00 1.05440000e-01
  1.18176400e-03 5.55148150e-02]]
[[998.97873704]]
[[5.98870370e-01 6.57500000e-01 0.00000000e+00 3.52253704e-01
  1.03968000e-04 6.46722220e-02]]
[[6.49629630e-01 6.38851852e-01 6.00000000e+00 1.05440000e-01
  1.18176400e-03 5.55148150e-02]]
[[146.02693445]]
[[0.47793205 0.5519337

[[0.74978571 0.70314286 9.         0.03418571 0.11570141 0.04269286]]
[[0.75558333 0.74141667 1.         0.2293775  0.00847702 0.05603333]]
[[755.62891401]]
[[0.60784615 0.79846154 7.         0.12981154 0.05987074 0.0599    ]]
[[0.75558333 0.74141667 1.         0.2293775  0.00847702 0.05603333]]
[[774.78832258]]
[[7.25527778e-01 8.18555556e-01 5.00000000e+00 1.29383333e-01
  4.12997800e-03 7.52750000e-02]]
[[0.75558333 0.74141667 1.         0.2293775  0.00847702 0.05603333]]
[[819.29923279]]
[[ 0.61804167  0.60941667 10.          0.08402158  0.12688008  0.10277083]]
[[ 0.716  0.649 10.     0.398  0.     0.056]]
[[999.3669787]]
[[0.63562295 0.61186885 1.         0.18145108 0.00897213 0.16926557]]
[[ 0.716  0.649 10.     0.398  0.     0.056]]
[[801.66719932]]
[[0.66808814 0.6425     0.         0.22149347 0.05059403 0.04797542]
 [0.66808814 0.6425     0.         0.22149347 0.05059403 0.04797542]]
[[ 0.716  0.649 10.     0.398  0.     0.056]]
[[102.64466747]
 [102.64466747]]
[[5.59950980e-

[[0.2876     0.36165333 8.         0.8384     0.07775666 0.03335333]]
[[0.41579902 0.53737366 5.         0.64181171 0.0434054  0.04934781]]
[[996.78427219]]
[[ 0.76671212  0.72469697 10.          0.25560606  0.15824215  0.10041667]]
[[0.41579902 0.53737366 5.         0.64181171 0.0434054  0.04934781]]
[[994.25646557]]
[[0.33090625 0.49870625 2.         0.5191375  0.07051707 0.041875  ]]
[[0.41579902 0.53737366 5.         0.64181171 0.0434054  0.04934781]]
[[981.06745442]]
[[0.42630768 0.6212495  0.         0.74141186 0.05362297 0.05827848]]
[[0.41579902 0.53737366 5.         0.64181171 0.0434054  0.04934781]]
[[183.99140537]]
[[0.57769879 0.69615422 9.         0.26895422 0.08694149 0.07002892]]
[[0.41579902 0.53737366 5.         0.64181171 0.0434054  0.04934781]]
[[994.7068912]]
[[4.620e-01 7.996e-01 1.000e+01 7.516e-01 4.680e-07 5.230e-02]]
[[0.41579902 0.53737366 5.         0.64181171 0.0434054  0.04934781]]
[[997.58748103]]
[[4.41692188e-01 6.36578125e-01 5.00000000e+00 6.50764063e-

[[6.89000000e-01 8.07444444e-01 1.10000000e+01 5.12100000e-02
  6.87264400e-03 3.94222220e-02]]
[[7.4875e-01 6.3225e-01 0.0000e+00 1.1190e-01 1.2323e-04 4.6800e-02]]
[[94.74931253]]
[[0.59526816 0.54763363 0.         0.25457736 0.07640244 0.0597657 ]]
[[7.4875e-01 6.3225e-01 0.0000e+00 1.1190e-01 1.2323e-04 4.6800e-02]]
[[976.79451445]]
[[6.75333333e-01 6.99500000e-01 9.00000000e+00 2.13058333e-01
  7.44142000e-03 3.59500000e-02]]
[[7.4875e-01 6.3225e-01 0.0000e+00 1.1190e-01 1.2323e-04 4.6800e-02]]
[[108.86870158]]
[[5.58975e-01 6.20225e-01 5.00000e+00 3.91570e-01 7.24883e-04 3.26075e-02]]
[[7.4875e-01 6.3225e-01 0.0000e+00 1.1190e-01 1.2323e-04 4.6800e-02]]
[[170.49721841]]
[[0.37375    0.6275     0.         0.491      0.01268025 0.040925  ]]
[[0.577      0.78466667 5.         0.2227     0.0062481  0.09306667]]
[[182.77091279]]
[[0.53099308 0.65028462 2.         0.58233681 0.04533749 0.07440461]]
[[0.577      0.78466667 5.         0.2227     0.0062481  0.09306667]]
[[955.64856845]]
[

  4.9062500e-02]]
[[0.79242105 0.73384211 2.         0.11756632 0.10278696 0.07523158]]
[[961.37907165]]
[[2.18e-01 5.52e-01 1.10e+01 5.48e-04 7.88e-01 6.53e-02]]
[[0.79242105 0.73384211 2.         0.11756632 0.10278696 0.07523158]]
[[900.19678438]]
[[5.6568750e-01 7.8750000e-01 7.0000000e+00 6.4369375e-02 4.4200000e-05
  2.7746250e-01]]
[[7.2480e-01 8.3250e-01 1.1000e+01 2.0560e-01 1.9800e-07 2.2234e-01]]
[[999.0052256]]
[[4.75e-01 7.24e-01 9.00e+00 3.67e-01 9.14e-06 1.70e-01]]
[[7.2480e-01 8.3250e-01 1.1000e+01 2.0560e-01 1.9800e-07 2.2234e-01]]
[[999.6616547]]
[[6.45e-01 7.81e-01 9.00e+00 2.93e-01 9.20e-04 6.62e-02]]
[[7.2480e-01 8.3250e-01 1.1000e+01 2.0560e-01 1.9800e-07 2.2234e-01]]
[[999.74717468]]
[[0.3558     0.7398     9.         0.2988     0.26207266 0.22364   ]]
[[7.2480e-01 8.3250e-01 1.1000e+01 2.0560e-01 1.9800e-07 2.2234e-01]]
[[999.10118809]]
[[5.97585366e-01 7.83121951e-01 1.00000000e+01 1.47239024e-01
  2.59000000e-06 2.55309756e-01]]
[[7.2480e-01 8.3250e-01 1.1000e+

[[0.63671053 0.57900263 7.         0.21446261 0.03825253 0.04262237]]
[[0.56507018 0.68236842 7.         0.19732695 0.03235    0.03807719]]
[[999.83778466]]
[[0.41189655 0.80086207 7.         0.69217241 0.00821427 0.03995517]]
[[0.56507018 0.68236842 7.         0.19732695 0.03235    0.03807719]]
[[997.18450562]]
[[0.62428938 0.52587063 5.         0.23682707 0.02246099 0.0514625 ]]
[[0.56507018 0.68236842 7.         0.19732695 0.03235    0.03807719]]
[[998.84540912]]
[[3.53845e-01 4.42600e-01 0.00000e+00 6.76900e-01 6.14276e-04 5.88850e-02]]
[[0.56507018 0.68236842 7.         0.19732695 0.03235    0.03807719]]
[[102.12623211]]
[[2.70669613e-01 6.50917127e-01 4.00000000e+00 8.44102210e-01
  7.79645000e-04 3.63005520e-02]]
[[0.56507018 0.68236842 7.         0.19732695 0.03235    0.03807719]]
[[982.28099915]]
[[0.37410408 0.49871379 2.         0.6073788  0.03648683 0.04569573]]
[[0.56507018 0.68236842 7.         0.19732695 0.03235    0.03807719]]
[[952.76096848]]
[[0.64021739 0.60771014 2.

[[999.26805176]]
[[0.70371429 0.61861905 0.         0.03482117 0.19303237 0.04828095]]
[[9.585000e-01 1.823750e-01 1.100000e+01 2.160225e-03 7.217500e-01
  9.200000e-02]]
[[87.78183018]]
[[0.5968   0.44035  1.       0.067564 0.5904   0.05192 ]]
[[9.585000e-01 1.823750e-01 1.100000e+01 2.160225e-03 7.217500e-01
  9.200000e-02]]
[[790.86486589]]
[[0.33766042 0.45492797 0.         0.71042288 0.08813228 0.09591186]]
[[9.585000e-01 1.823750e-01 1.100000e+01 2.160225e-03 7.217500e-01
  9.200000e-02]]
[[47.3055512]]
[[0.888 0.433 0.    0.11  0.872 0.132]]
[[9.585000e-01 1.823750e-01 1.100000e+01 2.160225e-03 7.217500e-01
  9.200000e-02]]
[[106.87886832]]
[[0.73131579 0.66997368 2.         0.30956466 0.24426504 0.04764737]]
[[9.585000e-01 1.823750e-01 1.100000e+01 2.160225e-03 7.217500e-01
  9.200000e-02]]
[[916.71614012]]
[[0.2408    0.4553    8.        0.3169718 0.7778    0.10952  ]]
[[9.585000e-01 1.823750e-01 1.100000e+01 2.160225e-03 7.217500e-01
  9.200000e-02]]
[[996.32101568]]
[[0.495 

[[ 0.73925     0.30357292 11.          0.23749881  0.20961086  0.10135417]]
[[8.36e-01 5.41e-01 7.00e+00 2.32e-05 2.91e-01 6.30e-02]]
[[996.98875328]]
[[0.821    0.47575  1.       0.097891 0.31545  0.073075]]
[[8.36e-01 5.41e-01 7.00e+00 2.32e-05 2.91e-01 6.30e-02]]
[[800.41147764]]
[[0.93016    0.58028    4.         0.03710368 0.16262696 0.128004  ]]
[[8.36e-01 5.41e-01 7.00e+00 2.32e-05 2.91e-01 6.30e-02]]
[[991.77668706]]
[[0.88137838 0.73064324 9.         0.05209419 0.10484253 0.06568851]]
[[8.36e-01 5.41e-01 7.00e+00 2.32e-05 2.91e-01 6.30e-02]]
[[999.31259837]]
[[0.767  0.605  7.     0.0409 0.     0.0785]]
[[8.36e-01 5.41e-01 7.00e+00 2.32e-05 2.91e-01 6.30e-02]]
[[999.04660854]]
[[9.72600000e-01 2.75926667e-01 9.00000000e+00 5.17580000e-04
  3.16040536e-01 1.44080000e-01]]
[[8.36e-01 5.41e-01 7.00e+00 2.32e-05 2.91e-01 6.30e-02]]
[[998.83184666]]
[[9.59666667e-01 2.24333333e-01 4.00000000e+00 5.30220000e-03
  8.01567000e-04 1.49000000e-01]]
[[8.36e-01 5.41e-01 7.00e+00 2.32e-05 

[[996.9047187]]
[[0.57950541 0.38014595 2.         0.16597181 0.11997386 0.04218108]]
[[0.57264359 0.32479103 8.         0.10884333 0.63319169 0.0392782 ]]
[[966.30220671]]
[[0.78668333 0.56569667 9.         0.08976605 0.11617692 0.05035167]]
[[0.57264359 0.32479103 8.         0.10884333 0.63319169 0.0392782 ]]
[[997.45849476]]
[[0.69924591 0.57183315 9.         0.18189168 0.32082536 0.05676298]]
[[0.57264359 0.32479103 8.         0.10884333 0.63319169 0.0392782 ]]
[[998.7649686]]
[[0.6888432  0.50598757 2.         0.22353723 0.15842088 0.06207041]]
[[0.57264359 0.32479103 8.         0.10884333 0.63319169 0.0392782 ]]
[[944.83108765]]
[[0.56325    0.478875   0.         0.13023495 0.29670097 0.0464125 ]]
[[0.57264359 0.32479103 8.         0.10884333 0.63319169 0.0392782 ]]
[[104.73817978]]
[[8.66857143e-01 4.09142857e-01 4.00000000e+00 1.75586000e-04
  5.89285714e-01 5.47714290e-02]]
[[0.57264359 0.32479103 8.         0.10884333 0.63319169 0.0392782 ]]
[[986.26155062]]
[[0.9284     0.38

[[998.93814101]]
[[0.85727225 0.55270733 1.         0.17069092 0.0735082  0.08195393]]
[[0.72286517 0.38778764 7.         0.14227474 0.05711319 0.04802921]]
[[773.39499415]]
[[0.56039474 0.57202632 7.         0.26730229 0.11598623 0.04434737]]
[[0.72286517 0.38778764 7.         0.14227474 0.05711319 0.04802921]]
[[999.20094355]]
[[0.50487102 0.57370694 9.         0.38778465 0.07285561 0.08965959]]
[[0.72286517 0.38778764 7.         0.14227474 0.05711319 0.04802921]]
[[998.60827179]]
[[0.559425   0.46967308 7.         0.29851673 0.0307104  0.03819423]]
[[0.72286517 0.38778764 7.         0.14227474 0.05711319 0.04802921]]
[[999.4100506]]
[[0.65918672 0.71942739 2.         0.1238621  0.13065461 0.04532822]]
[[0.72286517 0.38778764 7.         0.14227474 0.05711319 0.04802921]]
[[939.03471306]]
[[0.6888432  0.50598757 2.         0.22353723 0.15842088 0.06207041]]
[[0.72286517 0.38778764 7.         0.14227474 0.05711319 0.04802921]]
[[953.27463523]]
[[0.8918     0.4187     9.         0.04790

[[0.73766667 0.48006667 2.         0.0121886  0.24095778 0.04964444]]
[[6.52238095e-01 3.53076190e-01 9.00000000e+00 1.32031619e-01
  4.20127000e-04 2.91904760e-02]]
[[939.27994351]]
[[0.76262222 0.43515556 9.         0.1266736  0.14160465 0.07359778]]
[[6.52238095e-01 3.53076190e-01 9.00000000e+00 1.32031619e-01
  4.20127000e-04 2.91904760e-02]]
[[999.7510531]]
[[6.74941176e-01 4.78823529e-01 3.00000000e+00 1.72982353e-01
  3.95527000e-04 5.39176470e-02]]
[[6.52238095e-01 3.53076190e-01 9.00000000e+00 1.32031619e-01
  4.20127000e-04 2.91904760e-02]]
[[981.51635531]]
[[0.539125   0.4125     9.         0.31923475 0.343675   0.0558    ]]
[[6.52238095e-01 3.53076190e-01 9.00000000e+00 1.32031619e-01
  4.20127000e-04 2.91904760e-02]]
[[998.95951322]]
[[0.68015432 0.43948537 8.         0.12351189 0.12839654 0.04554789]]
[[6.52238095e-01 3.53076190e-01 9.00000000e+00 1.32031619e-01
  4.20127000e-04 2.91904760e-02]]
[[999.67127567]]
[[0.9284     0.38891    0.         0.0184954  0.10863052 0.0

[[0.43337308 0.60280769 9.         0.48855    0.09161272 0.04731731]]
[[0.62427014 0.63228152 0.         0.38096019 0.04083096 0.06341659]]
[[96.29614898]]
[[0.369   0.579   4.      0.933   0.00534 0.05   ]]
[[5.600625e-01 5.756250e-01 5.000000e+00 3.374000e-01 6.134410e-04
  8.558750e-02]]
[[986.70914098]]
[[0.71865714 0.66897143 2.         0.23262914 0.03913248 0.07050571]]
[[5.600625e-01 5.756250e-01 5.000000e+00 3.374000e-01 6.134410e-04
  8.558750e-02]]
[[955.51597819]]
[[0.57538636 0.43810682 1.         0.32392918 0.59998659 0.07745682]]
[[5.600625e-01 5.756250e-01 5.000000e+00 3.374000e-01 6.134410e-04
  8.558750e-02]]
[[793.94229621]]
[[0.56325    0.478875   0.         0.13023495 0.29670097 0.0464125 ]]
[[5.600625e-01 5.756250e-01 5.000000e+00 3.374000e-01 6.134410e-04
  8.558750e-02]]
[[155.74659176]]
[[3.22833333e-01 4.67095833e-01 9.00000000e+00 6.58291667e-01
  8.07793900e-03 3.89458330e-02]]
[[5.600625e-01 5.756250e-01 5.000000e+00 3.374000e-01 6.134410e-04
  8.558750e-02]

  4.60000000e-07 6.60666670e-02]]
[[0.36583426 0.49801852 2.         0.60655833 0.03740496 0.05070556]]
[[956.34428674]]
[[0.42630768 0.6212495  0.         0.74141186 0.05362297 0.05827848]]
[[0.36583426 0.49801852 2.         0.60655833 0.03740496 0.05070556]]
[[398.07462586]]
[[0.68666667 0.81573333 8.         0.52666667 0.09130326 0.04227333]]
[[0.36583426 0.49801852 2.         0.60655833 0.03740496 0.05070556]]
[[962.97081357]]
[[4.41692188e-01 6.36578125e-01 5.00000000e+00 6.50764063e-01
  6.19583000e-04 5.82125000e-02]]
[[0.36583426 0.49801852 2.         0.60655833 0.03740496 0.05070556]]
[[977.80053718]]
[[0.11050533 0.41947    9.         0.9062     0.02219243 0.06045667]]
[[0.36583426 0.49801852 2.         0.60655833 0.03740496 0.05070556]]
[[952.27888128]]
[[0.57978626 0.66227939 2.         0.33432829 0.05913408 0.03778244]]
[[0.36583426 0.49801852 2.         0.60655833 0.03740496 0.05070556]]
[[984.80726748]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]

 [0.79825581 0.28780698 2.         0.10308426 0.08968926 0.05213023]]
[[4.29e-01 1.87e-01 1.10e+01 1.02e-02 9.34e-06 2.59e-02]]
[[934.28792185]
 [934.28792185]]
[[0.7765     0.5003125  7.         0.06898432 0.1456932  0.05190625]]
[[4.29e-01 1.87e-01 1.10e+01 1.02e-02 9.34e-06 2.59e-02]]
[[995.73477259]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]]
[[4.29e-01 1.87e-01 1.10e+01 1.02e-02 9.34e-06 2.59e-02]]
[[35.69436952]]
[[0.73056    0.64108    9.         0.1177532  0.06412213 0.046092  ]]
[[4.29e-01 1.87e-01 1.10e+01 1.02e-02 9.34e-06 2.59e-02]]
[[997.56643093]]
[[0.76953719 0.64350331 4.         0.10807343 0.0737215  0.04690083]]
[[4.29e-01 1.87e-01 1.10e+01 1.02e-02 9.34e-06 2.59e-02]]
[[978.50043168]]
[[0.87050943 0.36531509 2.         0.02401414 0.17617931 0.08855472]]
[[9.57500e-01 2.61500e-01 2.00000e+00 8.36000e-05 2.18615e-03 1.31500e-01]]
[[994.88810004]]
[[9.68047619e-01 1.92529762e-01 8.00000000e+00 5.41722000e-04
  1.97283337e-01 1.25594048e-01]]
[

[[0.76953719 0.64350331 4.         0.10807343 0.0737215  0.04690083]]
[[9.360000e-01 5.350000e-01 6.000000e+00 2.542325e-03 4.190000e-05
  7.665000e-02]]
[[996.52966101]]
[[9.32500000e-01 5.76166667e-01 4.00000000e+00 1.75898330e-02
  8.64000000e-06 8.67750000e-02]]
[[9.360000e-01 5.350000e-01 6.000000e+00 2.542325e-03 4.190000e-05
  7.665000e-02]]
[[995.91311282]]
[[0.20136804 0.49893443 5.         0.90849863 0.01306362 0.06243178]]
[[5.0620e-01 3.6250e-01 9.0000e+00 3.1298e-01 2.0180e-04 3.5890e-02]]
[[987.76045016]]
[[5.18800000e-01 6.93233333e-01 1.00000000e+01 2.46287667e-01
  1.75277000e-04 4.24166670e-02]]
[[5.0620e-01 3.6250e-01 9.0000e+00 3.1298e-01 2.0180e-04 3.5890e-02]]
[[999.52107979]]
[[0.24163731 0.39109583 0.         0.83241367 0.00505954 0.06049189]]
[[5.0620e-01 3.6250e-01 9.0000e+00 3.1298e-01 2.0180e-04 3.5890e-02]]
[[61.24414508]]
[[0.55729336 0.64976458 0.         0.42324421 0.13706214 0.04991384]]
[[5.0620e-01 3.6250e-01 9.0000e+00 3.1298e-01 2.0180e-04 3.5890e-0

[[999.7092384]]
[[0.869  0.194  4.     0.42   0.     0.0925]]
[[7.59888889e-01 4.35518519e-01 9.00000000e+00 5.08784260e-02
  5.66291400e-03 4.48407410e-02]]
[[986.86113851]]
[[0.7644359  0.45023333 2.         0.01088907 0.20448619 0.06314103]]
[[0.607      0.456625   7.         0.00837972 0.09196875 0.090175  ]]
[[949.12795974]]
[[6.56735294e-01 4.97676471e-01 9.00000000e+00 2.72360294e-01
  5.33797000e-03 1.08711765e-01]]
[[0.607      0.456625   7.         0.00837972 0.09196875 0.090175  ]]
[[999.36255213]]
[[0.50337514 0.55496723 2.         0.34072034 0.16738794 0.04271356]]
[[0.607      0.456625   7.         0.00837972 0.09196875 0.090175  ]]
[[954.31100143]]
[[0.71865714 0.66897143 2.         0.23262914 0.03913248 0.07050571]]
[[9.44833333e-01 5.98166667e-01 2.00000000e+00 1.58156700e-03
  1.38453000e-04 5.96166670e-02]]
[[989.42893398]]
[[9.68047619e-01 1.92529762e-01 8.00000000e+00 5.41722000e-04
  1.97283337e-01 1.25594048e-01]]
[[9.44833333e-01 5.98166667e-01 2.00000000e+00 1.

[[998.29615613]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]]
[[0.53213078 0.63395654 9.         0.39848825 0.11536291 0.04397062]]
[[102.10862258]]
[[3.04280000e-01 4.01653333e-01 3.00000000e+00 8.54560000e-01
  8.76734000e-04 3.17680000e-02]]
[[0.53213078 0.63395654 9.         0.39848825 0.11536291 0.04397062]]
[[970.9245102]]
[[0.47793205 0.5519337  7.         0.56256679 0.03421143 0.06453489]]
[[0.5955     0.755      2.         0.5855     0.35100127 0.04005   ]]
[[917.61697284]]
[[0.61643379 0.80975343 0.         0.6831663  0.12001024 0.06120228]]
[[0.5955     0.755      2.         0.5855     0.35100127 0.04005   ]]
[[496.96299972]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]]
[[0.5955     0.755      2.         0.5855     0.35100127 0.04005   ]]
[[487.84442901]]
[[0.12   0.101  0.     0.193  0.515  0.0424]]
[[0.5955     0.755      2.         0.5855     0.35100127 0.04005   ]]
[[332.79822537]]
[[0.71991498 0.65533179 0.         0.293

[[0.53099308 0.65028462 2.         0.58233681 0.04533749 0.07440461]]
[[3.37222222e-01 3.39777778e-01 7.00000000e+00 5.77111111e-01
  8.80000000e-06 3.86555560e-02]]
[[931.47992583]]
[[0.44687258 0.56067742 5.         0.5063629  0.01428119 0.04081613]]
[[3.37222222e-01 3.39777778e-01 7.00000000e+00 5.77111111e-01
  8.80000000e-06 3.86555560e-02]]
[[997.05261908]]
[[0.70285   0.71135   2.        0.3855468 0.0930794 0.04684  ]]
[[3.37222222e-01 3.39777778e-01 7.00000000e+00 5.77111111e-01
  8.80000000e-06 3.86555560e-02]]
[[919.43339678]]
[[0.5215303  0.53157576 0.         0.31512091 0.06300518 0.10444546]]
[[3.37222222e-01 3.39777778e-01 7.00000000e+00 5.77111111e-01
  8.80000000e-06 3.86555560e-02]]
[[94.2099109]]
[[0.56285907 0.65373057 7.         0.35756916 0.15113145 0.05233627]]
[[3.37222222e-01 3.39777778e-01 7.00000000e+00 5.77111111e-01
  8.80000000e-06 3.86555560e-02]]
[[997.78664697]]
[[5.11210526e-01 5.11000000e-01 2.00000000e+00 1.94915789e-01
  2.48108000e-04 4.48736840e-02

  9.85120000e-04 4.50454550e-02]]
[[4.224e-01 6.488e-01 1.000e+00 7.496e-01 8.960e-06 3.162e-01]]
[[739.22446013]]
[[0.143   0.432   5.      0.912   0.02095 0.078  ]]
[[4.224e-01 6.488e-01 1.000e+00 7.496e-01 8.960e-06 3.162e-01]]
[[788.21286522]]
[[0.29211268 0.54317857 0.         0.83263571 0.00822695 0.07568125]]
[[4.224e-01 6.488e-01 1.000e+00 7.496e-01 8.960e-06 3.162e-01]]
[[719.35540592]]
[[5.5062500e-01 8.2162500e-01 9.0000000e+00 7.5053125e-02 9.0231300e-04
  3.7012500e-02]]
[[3.71193548e-01 5.92806452e-01 1.00000000e+00 2.97903226e-01
  2.28000000e-05 2.91419350e-02]]
[[853.89897201]]
[[3.82689764e-01 5.11163780e-01 7.00000000e+00 4.05725197e-01
  6.69244000e-04 4.66606300e-02]]
[[3.71193548e-01 5.92806452e-01 1.00000000e+00 2.97903226e-01
  2.28000000e-05 2.91419350e-02]]
[[855.35837957]]
[[0.32368966 0.569      0.         0.76934483 0.71082069 0.04065172]]
[[3.71193548e-01 5.92806452e-01 1.00000000e+00 2.97903226e-01
  2.28000000e-05 2.91419350e-02]]
[[442.9566438]]
[[0.356

[[945.71939219]]
[[3.22833333e-01 4.67095833e-01 9.00000000e+00 6.58291667e-01
  8.07793900e-03 3.89458330e-02]]
[[6.68666667e-01 5.93666667e-01 7.00000000e+00 2.76733330e-02
  5.79667000e-04 5.56666670e-02]]
[[995.34468411]]
[[0.75947887 0.46582958 9.         0.05617168 0.46374492 0.06271268]]
[[6.68666667e-01 5.93666667e-01 7.00000000e+00 2.76733330e-02
  5.79667000e-04 5.56666670e-02]]
[[998.09483482]]
[[0.70371429 0.61861905 0.         0.03482117 0.19303237 0.04828095]]
[[6.68666667e-01 5.93666667e-01 7.00000000e+00 2.76733330e-02
  5.79667000e-04 5.56666670e-02]]
[[124.4142845]]
[[0.939      0.40131579 9.         0.02691772 0.03909114 0.10735789]]
[[6.68666667e-01 5.93666667e-01 7.00000000e+00 2.76733330e-02
  5.79667000e-04 5.56666670e-02]]
[[999.14888367]]
[[0.5968   0.44035  1.       0.067564 0.5904   0.05192 ]]
[[6.68666667e-01 5.93666667e-01 7.00000000e+00 2.76733330e-02
  5.79667000e-04 5.56666670e-02]]
[[786.79993915]]
[[0.7644359  0.45023333 2.         0.01088907 0.2044861

[[0.39088235 0.56788235 5.         0.73658824 0.26248592 0.04891177]]
[[7.56e-01 8.82e-01 6.00e+00 2.11e-02 2.92e-04 2.39e-01]]
[[986.68422249]]
[[0.64440741 0.48776543 9.         0.18209259 0.05570974 0.05975062]]
[[0.72816667 0.3295     9.         0.11610267 0.565564   0.11505   ]]
[[998.17222669]]
[[0.908  0.641  4.     0.0731 0.503  0.0832]]
[[0.72816667 0.3295     9.         0.11610267 0.565564   0.11505   ]]
[[981.42058623]]
[[6.270e-01 7.325e-01 9.000e+00 2.725e-01 8.011e-03 4.765e-02]]
[[0.72816667 0.3295     9.         0.11610267 0.565564   0.11505   ]]
[[996.87477628]]
[[0.62692478 0.58169558 9.         0.23075863 0.13871765 0.11133673]]
[[0.72816667 0.3295     9.         0.11610267 0.565564   0.11505   ]]
[[998.35701924]]
[[0.6888432  0.50598757 2.         0.22353723 0.15842088 0.06207041]]
[[0.72816667 0.3295     9.         0.11610267 0.565564   0.11505   ]]
[[946.31185924]]
[[0.52   0.0628 7.     0.0301 0.788  0.0275]]
[[0.72816667 0.3295     9.         0.11610267 0.565564

[[0.3945   0.307    5.       0.71575  0.56699  0.040625]]
[[0.306  0.0432 8.     0.427  0.837  0.0343]]
[[993.80731842]]
[[0.72913605 0.71876191 2.         0.12987792 0.02871125 0.04542177]]
[[0.55042105 0.71078947 6.         0.08384874 0.03953226 0.03555263]]
[[946.25941452]]
[[0.56325    0.478875   0.         0.13023495 0.29670097 0.0464125 ]]
[[0.55042105 0.71078947 6.         0.08384874 0.03953226 0.03555263]]
[[137.52672848]]
[[3.60500000e-01 4.49250000e-01 7.00000000e+00 7.96083333e-01
  9.71450000e-04 2.06883333e-01]]
[[0.55042105 0.71078947 6.         0.08384874 0.03953226 0.03555263]]
[[992.60257004]]
[[0.70197143 0.72185714 9.         0.13827434 0.22946281 0.03689143]]
[[0.55042105 0.71078947 6.         0.08384874 0.03953226 0.03555263]]
[[999.02068982]]
[[0.59526816 0.54763363 0.         0.25457736 0.07640244 0.0597657 ]]
[[0.55042105 0.71078947 6.         0.08384874 0.03953226 0.03555263]]
[[143.54322928]]
[[0.7213     0.5955     9.         0.116133   0.13999884 0.04645   ]

[[990.20257811]]
[[0.41247059 0.61450267 2.         0.51584064 0.01694326 0.04372941]]
[[4.15208955e-01 6.32228358e-01 4.00000000e+00 6.31588060e-01
  2.32650000e-04 3.20805970e-02]]
[[982.97372914]]
[[2.70669613e-01 6.50917127e-01 4.00000000e+00 8.44102210e-01
  7.79645000e-04 3.63005520e-02]]
[[4.15208955e-01 6.32228358e-01 4.00000000e+00 6.31588060e-01
  2.32650000e-04 3.20805970e-02]]
[[998.08122476]]
[[ 0.3465      0.59970588 10.          0.53949412  0.11098313  0.03693529]]
[[4.15208955e-01 6.32228358e-01 4.00000000e+00 6.31588060e-01
  2.32650000e-04 3.20805970e-02]]
[[988.06918476]]
[[5.01355556e-01 7.38622222e-01 2.00000000e+00 4.33506667e-01
  7.93000000e-06 3.34022220e-02]]
[[0.64083333 0.84516667 1.         0.25148333 0.04401212 0.0974    ]]
[[923.33870711]]
[[0.45075    0.65070833 1.         0.62446042 0.00984686 0.0517625 ]]
[[0.64083333 0.84516667 1.         0.25148333 0.04401212 0.0974    ]]
[[949.59739994]]
[[0.63188   0.74376   2.        0.502452  0.0611265 0.077836 ]

  4.251600e-02]]
[[7.10888889e-01 5.41866667e-01 7.00000000e+00 1.56805333e-01
  4.50891000e-04 3.75288890e-02]]
[[999.7464838]]
[[4.33426230e-01 5.16557377e-01 7.00000000e+00 4.23355410e-01
  5.00938000e-04 2.87278690e-02]]
[[7.10888889e-01 5.41866667e-01 7.00000000e+00 1.56805333e-01
  4.50891000e-04 3.75288890e-02]]
[[998.50622112]]
[[5.36890411e-01 5.62547945e-01 9.00000000e+00 3.19684932e-01
  4.95637000e-04 3.28246580e-02]]
[[7.10888889e-01 5.41866667e-01 7.00000000e+00 1.56805333e-01
  4.50891000e-04 3.75288890e-02]]
[[998.94512024]]
[[5.466e-01 6.991e-01 9.000e+00 4.897e-01 3.740e-07 6.885e-02]]
[[7.10888889e-01 5.41866667e-01 7.00000000e+00 1.56805333e-01
  4.50891000e-04 3.75288890e-02]]
[[998.67346531]]
[[3.55722222e-01 5.00611111e-01 2.00000000e+00 5.40444444e-01
  3.36842000e-04 2.93555560e-02]]
[[7.10888889e-01 5.41866667e-01 7.00000000e+00 1.56805333e-01
  4.50891000e-04 3.75288890e-02]]
[[957.77531849]]
[[0.17867273 0.20838182 1.         0.93136364 0.01309992 0.03696364

[[0.32885833 0.43034444 2.         0.69113889 0.02672924 0.08020278]]
[[9.470e-02 3.705e-01 1.100e+01 8.600e-01 2.230e-05 5.295e-02]]
[[944.31560488]]
[[0.20298636 0.34503333 9.         0.83375758 0.01751032 0.04454697]]
[[9.470e-02 3.705e-01 1.100e+01 8.600e-01 2.230e-05 5.295e-02]]
[[999.78871854]]
[[6.49166667e-01 4.55000000e-01 1.00000000e+01 5.82166667e-01
  1.25167000e-04 5.10500000e-01]]
[[9.41857143e-01 7.38285710e-02 1.00000000e+00 8.18857143e-01
  1.13000000e-06 9.12857143e-01]]
[[624.94279045]]
[[8.234e-01 3.134e-01 1.100e+01 9.364e-01 4.420e-05 9.052e-01]]
[[9.41857143e-01 7.38285710e-02 1.00000000e+00 8.18857143e-01
  1.13000000e-06 9.12857143e-01]]
[[653.94983289]]
[[4.48448276e-01 7.18689655e-01 5.00000000e+00 6.32417241e-01
  5.24000000e-05 4.44551720e-02]]
[[ 0.8084      0.69383333 10.          0.29013     0.09419568  0.13472333]]
[[992.72576498]]
[[ 0.55366667  0.87622222 10.          0.46277778  0.49485433  0.03853333]]
[[ 0.8084      0.69383333 10.          0.29013 

[[0.50571429 0.42228571 2.         0.25554021 0.02205556 0.03408571]]
[[8.07575758e-01 5.12800000e-01 4.00000000e+00 3.88263940e-02
  2.71931400e-03 5.84787880e-02]]
[[989.69752092]]
[[0.69296154 0.63909615 7.         0.18190579 0.06434752 0.04165769]]
[[8.07575758e-01 5.12800000e-01 4.00000000e+00 3.88263940e-02
  2.71931400e-03 5.84787880e-02]]
[[994.21781478]]
[[0.6737     0.6685     2.         0.36194333 0.10780848 0.05169667]]
[[8.07575758e-01 5.12800000e-01 4.00000000e+00 3.88263940e-02
  2.71931400e-03 5.84787880e-02]]
[[963.65013186]]
[[0.77986463 0.51890044 9.         0.16506723 0.0260743  0.06741485]]
[[8.07575758e-01 5.12800000e-01 4.00000000e+00 3.88263940e-02
  2.71931400e-03 5.84787880e-02]]
[[991.35969608]]
[[0.6094382  0.65666292 7.         0.28478135 0.04028922 0.03492472]]
[[8.07575758e-01 5.12800000e-01 4.00000000e+00 3.88263940e-02
  2.71931400e-03 5.84787880e-02]]
[[992.73677474]]
[[0.61816667 0.55958333 2.         0.18662519 0.32627339 0.04838889]]
[[8.07575758e-0

  1.99202315e-01 1.22325000e-01]]
[[9.397000e-01 4.118150e-01 8.000000e+00 1.806660e-03 2.028309e-02
  1.482900e-01]]
[[943.08628507]]
[[0.83006484 0.29160968 8.         0.01246648 0.26623775 0.0845129 ]]
[[9.397000e-01 4.118150e-01 8.000000e+00 1.806660e-03 2.028309e-02
  1.482900e-01]]
[[999.29996887]]
[[7.41000000e-01 5.33333333e-01 9.00000000e+00 4.40000000e-03
  3.77343300e-03 8.95000000e-02]]
[[9.397000e-01 4.118150e-01 8.000000e+00 1.806660e-03 2.028309e-02
  1.482900e-01]]
[[999.32770384]]
[[4.009375e-01 3.919250e-01 7.000000e+00 6.391250e-01 3.115102e-03
  4.955625e-02]]
[[2.17833333e-01 2.48714286e-01 1.00000000e+01 9.10095238e-01
  8.48553000e-04 6.95238100e-02]]
[[998.90269065]]
[[3.39366667e-01 6.14433333e-01 0.00000000e+00 8.47566667e-01
  9.95000000e-05 8.93666670e-02]]
[[2.17833333e-01 2.48714286e-01 1.00000000e+01 9.10095238e-01
  8.48553000e-04 6.95238100e-02]]
[[90.53682617]]
[[0.27967273 0.4818303  0.         0.81642424 0.00386168 0.05177879]]
[[2.17833333e-01 2.487

[[0.30822857 0.41786018 0.         0.65571081 0.205073   0.05457107]]
[[0.517125   0.76225    5.         0.10555    0.01469651 0.0369875 ]]
[[125.82600348]]
[[0.32841852 0.42137037 9.         0.68038519 0.46397428 0.04372593]]
[[0.517125   0.76225    5.         0.10555    0.01469651 0.0369875 ]]
[[989.80923076]]
[[0.56325    0.478875   0.         0.13023495 0.29670097 0.0464125 ]]
[[0.832      0.62973913 0.         0.07712824 0.12113367 0.04402609]]
[[959.94769506]]
[[0.56474667 0.37555697 7.         0.25449917 0.10525787 0.04692   ]]
[[0.832      0.62973913 0.         0.07712824 0.12113367 0.04402609]]
[[99.8424244]]
[[0.755    0.7245   7.       0.050325 0.10935  0.03585 ]]
[[0.832      0.62973913 0.         0.07712824 0.12113367 0.04402609]]
[[147.81813738]]
[[0.59235659 0.57925892 2.         0.42715814 0.12266223 0.06221783]]
[[0.832      0.62973913 0.         0.07712824 0.12113367 0.04402609]]
[[389.65636326]]
[[0.76157143 0.39674286 9.         0.08073429 0.80342857 0.03678571]]
[[

[[0.87146512 0.37291861 8.         0.11975931 0.19856847 0.0878814 ]]
[[0.64932258 0.55367742 7.         0.32652581 0.0125148  0.03772581]]
[[998.58231436]]
[[0.5725    0.4665    9.        0.3931    0.0936635 0.04795  ]]
[[0.64932258 0.55367742 7.         0.32652581 0.0125148  0.03772581]]
[[999.18101933]]
[[0.79047727 0.5363053  9.         0.07851088 0.03324141 0.04770303]]
[[0.64932258 0.55367742 7.         0.32652581 0.0125148  0.03772581]]
[[999.09355739]]
[[0.62292063 0.61961111 2.         0.331065   0.28413833 0.0440627 ]]
[[0.64932258 0.55367742 7.         0.32652581 0.0125148  0.03772581]]
[[944.81082222]]
[[0.54682697 0.61965954 0.         0.36035593 0.05190613 0.05339502]]
[[0.64932258 0.55367742 7.         0.32652581 0.0125148  0.03772581]]
[[128.1611755]]
[[7.18333333e-01 3.70333333e-01 0.00000000e+00 5.15526700e-03
  2.52000000e-05 4.38166670e-02]]
[[0.64932258 0.55367742 7.         0.32652581 0.0125148  0.03772581]]
[[118.1019389]]
[[0.75353243 0.39114595 9.         0.123

In [56]:
influenceGraph['Bob Dylan']['Steely Dan']

{'weight': array([[950.34487452]])}

In [116]:
idDict = {}
for i in range(len(artists)):
    idDict[artists['artist_id'][i]] = artists['artist_name'][i]
    artistDict[artists['artist_name'][i]] = artists['artist_id'][i]

influence = pd.read_csv('influence_data.csv')
iGraph = nx.DiGraph()
for artist in artists['artist_id']:
    iGraph.add_node(artist, weight = 0)
    
for i in range(len(influence)):
    influencer = influence["influencer_id"][i]
    follower = influence['follower_id'][i]
    
    iGraph.add_edge(influencer,follower)    

arts = []
artnames = []
scores = []
for node in iGraph.nodes():
    children = list(iGraph.successors(node))
    total = 0
    for child in children:
        total += iGraph.out_degree[child]
        
    iGraph.nodes[node]['weight'] = total
    arts.append(node)
    try:
        artnames.append(idDict[node])
    except KeyError:
        artnames.append('Unknown')
    scores.append(total)
    
   
a = pd.DataFrame({'artists':arts, 'names':artnames, 'scores':scores})
a = a.sort_values(by=['scores'], ascending = False)
print(a[:20])

      artists                   names  scores
15     754032             The Beatles   11237
4       66915               Bob Dylan    7928
5      894465      The Rolling Stones    6341
137    120521             Chuck Berry    5897
7      180228           Elvis Presley    4749
210    840402  The Velvet Underground    4380
176    824022          Little Richard    4371
147    354105            Jimi Hendrix    4312
201    549797           Hank Williams    4134
35     100160               The Kinks    4067
24     577627                 The Who    4025
33     531986             David Bowie    3727
158    128099             James Brown    3725
390    538677             Buddy Holly    3502
1258   418740             Sex Pistols    3317
623    562304             The Stooges    3240
185    608701            Muddy Waters    3228
459     55128              Bo Diddley    3169
17     139026            Led Zeppelin    3143
6       41874          The Beach Boys    2955
